/* ============================================================================
   rz-explain.js — RZExplain: the ONE shared tooltip/explanation engine.
   Owner mandate (2026-07-16): every parameter, menu, submenu and tab on every
   surface (calculators, articles, DCMOC, terminal) explains itself on hover —
   with the CONTENT centralized in a knowledge DB, never hardcoded per page.

   - Knowledge DB: js/rz-explain-db.js → window.RZ_EXPLAIN_DB
     (generated by tools/build-explain-db.py from glossary.html's 354 terms +
     tools/explain-extra.json curated entries — see EXPLAIN_ENGINE_STANDARD.md)
   - Attach explicitly:  <span data-explain="dscr">DSCR</span>
     or scan a container: <div data-explain-scan> … </div> → known aliases in
     label/heading/cell text get wired automatically (first occurrence each).
   - NESTED TERMS (owner mandate): aliases mentioned INSIDE a tooltip body are
     themselves hoverable — the panel navigates with a breadcrumb back-link.
   - A11y: triggers are focusable (tabindex=0, aria-describedby), Escape closes,
     touch = tap toggle, panel clamped to the viewport using its REAL rendered
     size, mobile <600px renders as a bottom sheet, reduced-motion honoured.
   Zero deps, ES5-safe, idempotent (window.__rzExplain guard), z-index above
   tier gates (100002).
   ============================================================================ */
(function () {
  'use strict';
  if (window.__rzExplain) return;
  window.__rzExplain = true;

  var PANEL_ID = 'rzExplainPanel';
  var SCAN_CAP = 300;           /* max auto-wired triggers per page */
  var HOVER_INTENT_MS = 150;
  var stack = [];               /* nested-term breadcrumb stack of keys */
  var openTimer = null, closeTimer = null;
  var currentTrigger = null;
  var aliasIndex = null;        /* lowercased alias → key */

  function db() { return (window.RZ_EXPLAIN_DB && window.RZ_EXPLAIN_DB.entries) || {}; }

  function buildAliasIndex() {
    if (aliasIndex) return aliasIndex;
    aliasIndex = {};
    var entries = db();
    for (var k in entries) {
      var e = entries[k];
      aliasIndex[k.toLowerCase()] = k;
      if (e.t) aliasIndex[String(e.t).replace(/\s*\(.*\)$/, '').toLowerCase()] = k;
      var al = e.aliases || [];
      for (var i = 0; i < al.length; i++) aliasIndex[String(al[i]).toLowerCase()] = k;
    }
    return aliasIndex;
  }

  function esc(s) {
    return String(s == null ? '' : s).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }

  /* ── CSS (self-injected, token-aware; falls back to slate palette) ── */
  function injectCss() {
    if (document.getElementById('rz-explain-css')) return;
    var css = [
      '.rzx-trigger{cursor:help;border-bottom:1px dotted currentColor;text-decoration:none;}',
      '.rzx-trigger:focus-visible{outline:2px solid #0ea5e9;outline-offset:2px;border-radius:3px;}',
      '#' + PANEL_ID + '{position:fixed;z-index:100002;max-width:380px;min-width:240px;display:none;',
      'background:var(--fs-bg2,var(--bg-secondary,#1e293b));color:var(--fs-t1,var(--text-primary,#f1f5f9));',
      'border:1px solid var(--fs-bd,var(--bg-tertiary,#334155));border-radius:12px;padding:14px 16px;',
      'box-shadow:0 12px 32px rgba(0,0,0,.35);font-size:.82rem;line-height:1.55;',
      "font-family:'IBM Plex Sans','Inter',system-ui,sans-serif;}",
      '[data-theme="light"] #' + PANEL_ID + '{background:#ffffff;color:#0f172a;border-color:#e2e8f0;box-shadow:0 12px 32px rgba(15,23,42,.18);}',
      '#' + PANEL_ID + ' .rzx-title{font-weight:700;font-size:.88rem;margin:0 0 6px;display:flex;align-items:center;gap:8px;flex-wrap:wrap;}',
      '#' + PANEL_ID + ' .rzx-back{cursor:pointer;border:1px solid var(--fs-bd,#334155);background:transparent;color:inherit;border-radius:6px;font-size:.66rem;padding:1px 8px;font-family:inherit;}',
      '#' + PANEL_ID + ' .rzx-body{margin:0;color:var(--fs-t2,var(--text-primary,#cbd5e1));}',
      '[data-theme="light"] #' + PANEL_ID + ' .rzx-body{color:#334155;}',
      '#' + PANEL_ID + ' .rzx-term{color:#38bdf8;border-bottom:1px dotted #38bdf8;cursor:help;}',
      '[data-theme="light"] #' + PANEL_ID + ' .rzx-term{color:#0369a1;border-bottom-color:#0369a1;}',
      '#' + PANEL_ID + ' .rzx-formula{margin:8px 0 0;padding:6px 10px;border-radius:8px;background:var(--fs-bg3,rgba(15,23,42,.6));',
      "font-family:'JetBrains Mono',monospace;font-size:.74rem;overflow-x:auto;white-space:pre-wrap;}",
      '[data-theme="light"] #' + PANEL_ID + ' .rzx-formula{background:#f1f5f9;}',
      '#' + PANEL_ID + ' table.rzx-table{width:100%;border-collapse:collapse;margin-top:8px;font-size:.72rem;}',
      '#' + PANEL_ID + ' table.rzx-table td{padding:3px 6px;border-bottom:1px dashed var(--fs-bd2,rgba(51,65,85,.4));}',
      '#' + PANEL_ID + ' .rzx-meta{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px;align-items:center;}',
      '#' + PANEL_ID + ' .rzx-chip{font-size:.6rem;font-weight:700;letter-spacing:.05em;text-transform:uppercase;',
      'padding:2px 8px;border-radius:99px;border:1px solid var(--fs-bd,#334155);color:var(--fs-t3,#94a3b8);}',
      '#' + PANEL_ID + ' .rzx-rel{font-size:.66rem;cursor:help;padding:2px 8px;border-radius:99px;background:rgba(56,189,248,.12);color:#38bdf8;border:1px solid rgba(56,189,248,.3);}',
      '[data-theme="light"] #' + PANEL_ID + ' .rzx-rel{color:#0369a1;background:rgba(3,105,161,.08);border-color:rgba(3,105,161,.3);}',
      '#' + PANEL_ID + ' a.rzx-gloss{font-size:.66rem;color:#38bdf8;}',
      '[data-theme="light"] #' + PANEL_ID + ' a.rzx-gloss{color:#0369a1;}',
      '@media (max-width:600px){#' + PANEL_ID + '{left:0!important;right:0!important;bottom:0!important;top:auto!important;',
      'max-width:none;border-radius:16px 16px 0 0;max-height:60vh;overflow-y:auto;}}',
      '@media (prefers-reduced-motion:no-preference){#' + PANEL_ID + '{transition:opacity .14s ease;}}'
    ].join('');
    var st = document.createElement('style');
    st.id = 'rz-explain-css';
    st.textContent = css;
    document.head.appendChild(st);
  }

  function panel() {
    var p = document.getElementById(PANEL_ID);
    if (!p) {
      p = document.createElement('div');
      p.id = PANEL_ID;
      p.setAttribute('role', 'tooltip');
      document.body.appendChild(p);
      /* panel itself keeps the tooltip open while hovered (so nested terms are reachable) */
      p.addEventListener('mouseenter', function () { clearTimeout(closeTimer); });
      p.addEventListener('mouseleave', function () { scheduleClose(); });
      /* nested-term navigation: hover or tap a term inside the body */
      p.addEventListener('mouseover', function (ev) {
        var t = ev.target.closest ? ev.target.closest('.rzx-term,.rzx-rel') : null;
        if (t && t.getAttribute('data-explain')) {
          clearTimeout(openTimer);
          openTimer = setTimeout(function () { navigate(t.getAttribute('data-explain')); }, HOVER_INTENT_MS);
        }
      });
      p.addEventListener('click', function (ev) {
        var b = ev.target.closest ? ev.target.closest('.rzx-back') : null;
        if (b) { ev.preventDefault(); goBack(); return; }
        var t = ev.target.closest ? ev.target.closest('.rzx-term,.rzx-rel') : null;
        if (t && t.getAttribute('data-explain')) { ev.preventDefault(); navigate(t.getAttribute('data-explain')); }
      });
    }
    return p;
  }

  /* wrap known aliases inside body text so terms-in-tooltips explain themselves.
     Two-pass: collect non-overlapping match ranges on the PLAIN text first, then
     assemble the HTML once — so later aliases can never match inside the markup
     of an earlier insertion (the opex-inside-data-attribute bug). */
  function linkTerms(text, selfKey) {
    var idx = buildAliasIndex();
    var plain = String(text || '');
    var aliases = [];
    for (var a in idx) if (idx[a] !== selfKey && a.length >= 3) aliases.push(a);
    aliases.sort(function (x, y) { return y.length - x.length; });
    var lower = plain.toLowerCase();
    var ranges = [], usedKeys = {};
    function overlaps(st, en) {
      for (var i = 0; i < ranges.length; i++) if (st < ranges[i].en && en > ranges[i].st) return true;
      return false;
    }
    for (var i = 0; i < aliases.length && ranges.length < 8; i++) {
      var key = idx[aliases[i]];
      if (usedKeys[key]) continue;
      var pos = lower.indexOf(aliases[i]);
      while (pos !== -1) {
        var en = pos + aliases[i].length;
        var before = pos === 0 ? '' : plain[pos - 1];
        var after = plain[en] || '';
        if (!/[\w-]/.test(before) && !/[\w-]/.test(after) && !overlaps(pos, en)) {
          ranges.push({ st: pos, en: en, key: key });
          usedKeys[key] = 1;
          break;
        }
        pos = lower.indexOf(aliases[i], pos + 1);
      }
    }
    ranges.sort(function (x, y) { return x.st - y.st; });
    var out = '', cursor = 0;
    for (var r = 0; r < ranges.length; r++) {
      out += esc(plain.slice(cursor, ranges[r].st));
      out += '<span class="rzx-term" data-explain="' + esc(ranges[r].key) + '" tabindex="0">' + esc(plain.slice(ranges[r].st, ranges[r].en)) + '</span>';
      cursor = ranges[r].en;
    }
    out += esc(plain.slice(cursor));
    return out;
  }

  function render(key) {
    var e = db()[key];
    if (!e) return false;
    var p = panel();
    var html = '<div class="rzx-title">';
    if (stack.length > 1) html += '<button type="button" class="rzx-back" aria-label="Back to previous term">← back</button>';
    html += esc(e.t || key) + '</div>';
    html += '<p class="rzx-body">' + linkTerms(e.d || '', key) + '</p>';
    if (e.f) html += '<div class="rzx-formula">' + esc(e.f) + '</div>';
    if (e.table && e.table.length) {
      html += '<table class="rzx-table">';
      for (var i = 0; i < Math.min(e.table.length, 6); i++) {
        html += '<tr><td>' + esc(e.table[i][0]) + '</td><td style="text-align:right;font-family:\'JetBrains Mono\',monospace;">' + esc(e.table[i][1]) + '</td></tr>';
      }
      html += '</table>';
    }
    var meta = '';
    if (e.u) meta += '<span class="rzx-chip">' + esc(e.u) + '</span>';
    if (e.s) meta += '<span class="rzx-chip" title="Source">' + esc(e.s) + '</span>';
    var rel = e.rel || [];
    for (var r = 0; r < Math.min(rel.length, 4); r++) {
      var re2 = db()[rel[r]];
      if (re2) meta += '<span class="rzx-rel" data-explain="' + esc(rel[r]) + '" tabindex="0">' + esc(re2.t ? String(re2.t).replace(/\s*\(.*\)$/, '') : rel[r]) + '</span>';
    }
    if (e.link) meta += '<a class="rzx-gloss" href="' + esc(e.link) + '">Glossary →</a>';
    if (meta) html += '<div class="rzx-meta">' + meta + '</div>';
    p.innerHTML = html;
    return true;
  }

  function position(trigger) {
    var p = panel();
    p.style.display = 'block';
    p.style.opacity = '0';
    if (window.innerWidth <= 600) { p.style.opacity = '1'; return; }   /* bottom sheet via CSS */
    var r = trigger.getBoundingClientRect();
    /* measure with REAL size after display (spares-tour lesson) */
    var pw = p.offsetWidth, ph = p.offsetHeight;
    var top = r.bottom + 8;
    if (top + ph > window.innerHeight - 8) top = r.top - ph - 8;
    if (top < 8) top = 8;
    var left = Math.min(Math.max(8, r.left), window.innerWidth - pw - 8);
    p.style.top = top + 'px';
    p.style.left = left + 'px';
    p.style.right = 'auto';
    p.style.bottom = 'auto';
    p.style.opacity = '1';
  }

  function openFor(trigger, key) {
    if (!render(key)) return;
    currentTrigger = trigger;
    stack = [key];
    position(trigger);
    if (trigger && trigger.setAttribute) trigger.setAttribute('aria-describedby', PANEL_ID);
  }

  function navigate(key) {
    if (stack[stack.length - 1] === key) return;
    stack.push(key);
    if (render(key) && currentTrigger) position(currentTrigger);
  }

  function goBack() {
    if (stack.length < 2) return;
    stack.pop();
    var key = stack[stack.length - 1];
    /* re-render without pushing */
    var keep = stack.slice();
    render(key);
    stack = keep;
    if (currentTrigger) position(currentTrigger);
  }

  function close() {
    var p = document.getElementById(PANEL_ID);
    if (p) p.style.display = 'none';
    if (currentTrigger && currentTrigger.removeAttribute) currentTrigger.removeAttribute('aria-describedby');
    currentTrigger = null;
    stack = [];
  }

  function scheduleClose() {
    clearTimeout(closeTimer);
    closeTimer = setTimeout(close, 220);
  }

  function wire(el, key) {
    if (el.__rzxWired) return;
    el.__rzxWired = true;
    el.classList.add('rzx-trigger');
    if (!el.hasAttribute('tabindex')) el.setAttribute('tabindex', '0');
    el.addEventListener('mouseenter', function () {
      clearTimeout(closeTimer);
      clearTimeout(openTimer);
      openTimer = setTimeout(function () { openFor(el, key); }, HOVER_INTENT_MS);
    });
    el.addEventListener('mouseleave', function () { clearTimeout(openTimer); scheduleClose(); });
    el.addEventListener('focus', function () { clearTimeout(closeTimer); openFor(el, key); });
    el.addEventListener('blur', function () { scheduleClose(); });
    el.addEventListener('touchend', function (ev) {
      if (currentTrigger === el && document.getElementById(PANEL_ID) && document.getElementById(PANEL_ID).style.display === 'block') { close(); return; }
      ev.preventDefault();
      openFor(el, key);
    });
  }

  function attachExplicit(root) {
    var nodes = (root || document).querySelectorAll('[data-explain]');
    for (var i = 0; i < nodes.length; i++) {
      var key = nodes[i].getAttribute('data-explain');
      if (key && db()[key] && !nodes[i].closest('#' + PANEL_ID)) wire(nodes[i], key);
    }
  }

  /* auto-wire known aliases inside opted-in containers ([data-explain-scan]) —
     matches label/heading/cell/tab TEXT, first occurrence per key, capped */
  function scan(root) {
    var idx = buildAliasIndex();
    var containers = root ? [root] : document.querySelectorAll('[data-explain-scan]');
    var wired = 0, seen = {};
    for (var c = 0; c < containers.length && wired < SCAN_CAP; c++) {
      var cands = containers[c].querySelectorAll('label,th,h2,h3,h4,button,[role="tab"],dt,.metric-label,.input-label,.card-title,.tab');
      for (var i = 0; i < cands.length && wired < SCAN_CAP; i++) {
        var el = cands[i];
        if (el.hasAttribute('data-explain') || el.__rzxWired || el.closest('#' + PANEL_ID)) continue;
        var txt = (el.textContent || '').trim().replace(/\s+/g, ' ').replace(/[?？]\s*$/, '').trim();
        if (!txt || txt.length > 64) continue;
        var key = idx[txt.toLowerCase()];
        if (key && !seen[key]) { wire(el, key); seen[key] = 1; wired++; }
      }
    }
    return wired;
  }

  /* text-level scan for prose (articles/glossary): wraps the FIRST occurrence of
     each known alias in text nodes. TreeWalker, skips code/pre/a/script and already-
     wired nodes; capped so long articles stay fast. */
  function scanText(container, cap) {
    var idx = buildAliasIndex();
    cap = cap || 40;
    var aliases = [];
    for (var a in idx) if (a.length >= 4) aliases.push(a);
    aliases.sort(function (x, y) { return y.length - x.length; });
    var seen = {}, wired = 0;
    var walker = document.createTreeWalker(container, NodeFilter.SHOW_TEXT, {
      acceptNode: function (n) {
        if (!n.nodeValue || n.nodeValue.length < 4) return NodeFilter.FILTER_REJECT;
        var el = n.parentElement;
        if (!el || el.closest('svg,code,pre,a,script,style,button,[data-explain],#' + PANEL_ID)) return NodeFilter.FILTER_REJECT;
        return NodeFilter.FILTER_ACCEPT;
      }
    });
    var nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    for (var ni = 0; ni < nodes.length && wired < cap; ni++) {
      var node = nodes[ni], text = node.nodeValue;
      for (var i = 0; i < aliases.length && wired < cap; i++) {
        var key = idx[aliases[i]];
        if (seen[key]) continue;
        var pos = text.toLowerCase().indexOf(aliases[i]);
        if (pos < 0) continue;
        /* word-boundary check */
        var before = pos === 0 ? '' : text[pos - 1];
        var after = text[pos + aliases[i].length] || '';
        if (/\w/.test(before) || /\w/.test(after)) continue;
        var span = document.createElement('span');
        span.setAttribute('data-explain', key);
        span.textContent = text.substr(pos, aliases[i].length);
        var rest = node.splitText(pos);
        rest.nodeValue = rest.nodeValue.substr(aliases[i].length);
        node.parentNode.insertBefore(span, rest);
        wire(span, key);
        seen[key] = 1;
        wired++;
        node = rest;
        text = rest.nodeValue;
        i = -1; /* restart alias loop on the remainder node? no — keep going; avoid infinite */
        break;
      }
    }
    return wired;
  }

  function init() {
    injectCss();
    attachExplicit(document);
    scan();
    document.addEventListener('keydown', function (ev) {
      if (ev.key === 'Escape') close();
    });
    document.addEventListener('scroll', function () {
      if (currentTrigger && window.innerWidth > 600) close();
    }, { passive: true });
  }

  window.RZExplain = {
    attach: wire,
    attachExplicit: attachExplicit,
    scan: scan,
    scanText: scanText,
    open: function (key, el) { openFor(el || document.body, key); },
    close: close,
    has: function (key) { return !!db()[key]; },
    entry: function (key) { return db()[key] || null; }
  };

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
  else init();
})();
