/* ─── VALUE BINDING & SYNC CATALOG (Phase AH) ────────────────────────────────
 * Machine-readable registry of EVERY bound number in DC-OS: where it comes
 * from (source params), the formula, the engine function, and every consumer.
 * Rendered as the "Value Bindings" manual in the Knowledge Base + linked from
 * the FAQ; `data-bind` attributes on KPI elements reference these ids and the
 * synergy probe asserts cross-page equality per binding.
 * Owner mandate: "angka perhitungan saling sinergy, didokumentasikan per
 * point/value" — this file IS that documentation (single source).
 * ──────────────────────────────────────────────────────────────────────── */

export type BindingProvenance = 'input' | 'engine' | 'derived' | 'tracking' | 'assumption' | 'screening';

export interface ValueBinding {
    id: string;                       // stable id, doubles as data-bind anchor
    label: string;
    group: string;                    // catalog grouping
    pages: string[];                  // activeTab ids where the value renders
    sourceParams: string[];           // registry ids / store fields feeding it
    formula: string;                  // human-readable derivation
    engineFn?: string;                // rz-engine or module function
    consumers: string[];              // downstream values/pages reading it
    provenance: BindingProvenance;
    notes?: string;
}

export const VALUE_BINDINGS: ValueBinding[] = [
    /* ═══ 1 · SHARED CANONICALS (single source: sim + capex stores) ═══ */
    { id: 'sim.itLoad', label: 'IT Load (kW)', group: 'Shared canonicals', pages: ['requirements', 'capacity', 'architecture', 'capex', 'ops', 'commissioning', 'cdu', 'spares', 'site'], sourceParams: ['sim.itLoad'], formula: 'User input (Requirements 1.2) — writeSharedItLoad writes BOTH the simulation and capex stores in one call', consumers: ['capex.total', 'arch.facilityMw', 'equipScale fleet', 'opex.total', 'site analyses ctx', 'deep-sea flow'], provenance: 'input', notes: 'THE root parameter. Never duplicated: every page reads the same store field.' },
    { id: 'sim.tierLevel', label: 'Tier Level', group: 'Shared canonicals', pages: ['requirements', 'architecture', 'reliability', 'ops', 'capex', 'site'], sourceParams: ['sim.tierLevel'], formula: 'User input; use-case profile bumps it to the engine tierFloor when below', consumers: ['pueMatrix column', 'tierAvailability target', 'grid engine', 'battery autonomy annotation'], provenance: 'input' },
    { id: 'sim.coolingType', label: 'Cooling Type', group: 'Shared canonicals', pages: ['requirements', 'architecture', 'capacity', 'capex', 'cdu', 'sustainability'], sourceParams: ['sim.coolingType', 'sim.coolingTopology'], formula: 'User input (1.2 / use-case profile) — writeSharedCooling maps the UI key + topology into both stores', consumers: ['PUE', 'cooling lane of the diagram', 'CDU sizing', 'refrigerant auto-pick', 'capex cooling multiplier'], provenance: 'input' },
    { id: 'sim.powerRedundancy', label: 'Redundancy (N+1/2N/2N+1)', group: 'Shared canonicals', pages: ['architecture', 'reliability', 'capex', 'commissioning'], sourceParams: ['sim.powerRedundancy'], formula: 'User input; REDUNDANCY_KEY maps to engine keys n1/2n/2n1', consumers: ['redundancyPaths (A/B trunks + buses)', 'availability parallel paths', 'IST scenario count', 'capex redundancy multiplier'], provenance: 'input' },
    { id: 'sim.country', label: 'Country', group: 'Shared canonicals', pages: ['requirements', 'site', 'capex', 'ops', 'financial'], sourceParams: ['sim.selectedCountry', 'capex.location'], formula: 'writeSharedCountry(id) sets simulation.selectCountry AND capex.location+country in one call (region-grouped CountrySelect)', consumers: ['electricity rate', 'labor tables', 'grid/tax/disaster/talent/compliance engines', 'construction index', 'spares lead time'], provenance: 'input' },
    { id: 'req.avgRackDensityKw', label: 'Rack Density (kW/rack)', group: 'Shared canonicals', pages: ['requirements', 'architecture', 'capacity', 'assets', 'spares', 'commissioning'], sourceParams: ['req.workload.avgRackDensityKw'], formula: 'User input or use-case profile; writeSharedRackDensity also maps to the capex rackType class (≤8 std / ≤15 med / ≤35 high / >35 ai)', consumers: ['totalRacks', 'equipScale density bucket (<9 std, <18 med, <45 high, else ai_hpc)', 'capex rack multiplier'], provenance: 'input' },
    { id: 'req.designMarginPct', label: 'Design Margin %', group: 'Shared canonicals', pages: ['requirements', 'capex', 'architecture', 'financial'], sourceParams: ['req.business.designMarginPct'], formula: 'User input (1.5); the registry setter ALSO writes capex.contingency (same %) — capex auto-recalcs', consumers: ['capex.contingency line', 'grand total', 'financial budget baseline', 'diagram margin annotation'], provenance: 'input', notes: 'Owner margin mandate: one slider moves the money.' },
    { id: 'req.totalRacks', label: 'Total Racks', group: 'Shared canonicals', pages: ['requirements', 'architecture', 'capacity'], sourceParams: ['sim.itLoad', 'req.workload.avgRackDensityKw', 'req.workload.totalRacksOverride'], formula: 'ceil(itLoadKw ÷ densityKw); user override wins when set (effectiveTotalRacks)', consumers: ['diagram rack cells', 'leaf-switch count (÷16)', 'capacity rack utilization'], provenance: 'derived' },
    { id: 'req.workloadMix', label: 'Workload Mix %', group: 'Shared canonicals', pages: ['requirements', 'architecture'], sourceParams: ['req.workload.workloadMix', 'req.workload.mixManual'], formula: 'Use-case MIX_PRESETS applied on pick; manual-override tick unlocks the sliders (normalized to 100)', consumers: ['IT-hall cell split in the diagram', 'per-cell rack counts'], provenance: 'input' },

    /* ═══ 2 · CAPEX CHAIN ═══ */
    { id: 'capex.total', label: 'CAPEX Total (P50)', group: 'CAPEX chain', pages: ['dashboard', 'capex', 'finance', 'invest', 'report'], sourceParams: ['sim.itLoad', 'capex.* (all assumption fields)'], formula: 'Σ 14 costFactors × multipliers (redundancy·cooling·rack·building·seismic·country·year) + fees + contingency', engineFn: 'CapexEngine.calculateCapex', consumers: ['Financial budget baseline', 'Investment capitalization', 'Results $/kW score', 'site analyses ctx.totalCapex', 'EVM budget'], provenance: 'engine', notes: 'ONE number everywhere: Dashboard KPI = CAPEX P50 = Financial baseline = Investment total.' },
    { id: 'capex.perKw', label: 'CAPEX $/kW', group: 'CAPEX chain', pages: ['capex', 'report'], sourceParams: ['capex.total', 'sim.itLoad'], formula: 'capex.total ÷ itLoadKw', consumers: ['Results capex score (vs engine reference band)', 'benchmark position'], provenance: 'derived' },
    { id: 'capex.p80', label: 'CAPEX P80 / P10 band', group: 'CAPEX chain', pages: ['capex'], sourceParams: ['capex.total'], formula: 'Deterministic normal approx of the AACE Class-4 −30/+50 band: σ=(high−low)/2.5632; P80 = P50 + 0.8416σ', engineFn: 'models.capex.accuracyRange', consumers: ['risk curve', 'summary band'], provenance: 'engine', notes: 'No Math.random — reproducible band.' },
    { id: 'capex.contingency', label: 'Contingency %', group: 'CAPEX chain', pages: ['capex', 'requirements'], sourceParams: ['req.business.designMarginPct'], formula: 'BOUND to Design Margin (1.5) — display-only in 1.6 Delivery Basis', consumers: ['capex.total'], provenance: 'input' },
    { id: 'capex.deepSea', label: 'Deep-Sea Cooling fields', group: 'CAPEX chain', pages: ['requirements', 'capex', 'cdu'], sourceParams: ['capex.deepSea', 'capex.dsDepthM', 'capex.dsPipelineKm', 'capex.dsDeltaTC'], formula: 'Shared tick + params (Requirements 1.6 ≡ CAPEX drawer ≡ CDU advanced section — one store field)', engineFn: 'models.cooling.deepSea', consumers: ['CDU advanced section (flow, intake temp, pumps, chiller-less PUE, marine capex/opex)'], provenance: 'input' },

    /* ═══ 3 · PUE / ENERGY / OPEX ═══ */
    { id: 'pue.design', label: 'PUE (Design)', group: 'PUE & OPEX', pages: ['dashboard', 'architecture', 'ops', 'capacity', 'sustainability', 'report', 'cdu'], sourceParams: ['sim.coolingType', 'sim.tierLevel'], formula: "DATA.pueMatrix[coolingType]['tier'+tier] read DIRECTLY (never models.pue.defaultFor — its key map silently falls liquid→air)", engineFn: 'rzData().pueMatrix', consumers: ['facility MW', 'energy cost', 'carbon scopes', 'overhead donut split', 'Results sustainability score'], provenance: 'engine', notes: 'The catalogued engine trap: matrix-direct is the ONLY correct read.' },
    { id: 'arch.facilityMw', label: 'Facility Load (MW)', group: 'PUE & OPEX', pages: ['architecture', 'capacity', 'ops', 'sustainability'], sourceParams: ['sim.itLoad', 'pue.design'], formula: 'IT MW × PUE', consumers: ['design capacity checks', 'monthly energy = facility × 730h', 'gen capacity sizing'], provenance: 'derived' },
    { id: 'opex.totalAnnual', label: 'OPEX Annual', group: 'PUE & OPEX', pages: ['finance', 'report', 'site'], sourceParams: ['sim.itLoad', 'pue.design', 'sim.country', 'staff.headcounts', 'capex.total'], formula: "models.opex.totalAnnual(itMw, pue, countryId, months, {capex, basisPreset:'dcContract'}) — DC-contract blend @100% util (opex-calculator's own basis = retailScreening preset, documented divergence)", engineFn: 'models.opex.totalAnnual', consumers: ['Financial OPEX YTD (÷12×months)', 'Results LCOE-ish outcomes', 'site analyses ctx.annualOpex'], provenance: 'engine' },
    { id: 'ops.energyCostDay', label: 'Energy Cost / day', group: 'PUE & OPEX', pages: ['ops'], sourceParams: ['arch.facilityMw', 'sim.country'], formula: '24h × facility kW × country electricityRate', consumers: ['ops KPI'], provenance: 'derived' },
    { id: 'dashboard.projectCapacity', label: 'Project Capacity (MW)', group: 'PUE & OPEX', pages: ['dashboard'], sourceParams: ['sim.itLoad', 'req.designMarginPct'], formula: 'Design capacity = IT load × (1 + design margin) — NOT the same number as IT load by design', consumers: ['dashboard hero KPI'], provenance: 'derived', notes: 'The one owner-confusable pair: Dashboard 3 MW (design) vs 2.5 MW (IT). Both correct; basis chips label each.' },

    /* ═══ 4 · RELIABILITY & COMMISSIONING ═══ */
    { id: 'rel.availability', label: 'Composed Availability', group: 'Reliability & Cx', pages: ['reliability', 'risk', 'ops'], sourceParams: ['sim.powerRedundancy', 'sim.tierLevel'], formula: 'Series of per-system chains (component MTBF/MTTR → availability; parallel per redundancy paths with β=5% common-cause screening); shown in nines, downtime in min or s', engineFn: 'models.reliability.availability / DATA.reliability.components', consumers: ['downtime budget waterfall', 'Results ops score', 'risk page availability'], provenance: 'engine' },
    { id: 'rel.tierTarget', label: 'Tier Availability Target', group: 'Reliability & Cx', pages: ['reliability', 'ops', 'requirements'], sourceParams: ['sim.tierLevel'], formula: 'DATA.reliability.tierAvailability[tier] (e.g. Tier 3 = 99.982%) — a TARGET, never presented as measured', consumers: ['SLA check (1.4)', 'status chips vs composed availability'], provenance: 'engine' },
    { id: 'cx.readinessIndex', label: 'Readiness Index', group: 'Reliability & Cx', pages: ['commissioning'], sourceParams: ['cxTracking.completion', 'cxTracking.checklist'], formula: 'Engine weighted sum over L1..punchlist (weights: L5 0.22, ist 0.18, L4 0.15, L3 0.12 …); checklist-derived completion (pass/total per level) WINS over the coarse slider when ticks exist', engineFn: 'models.commissioning.readinessIndex', consumers: ['Ready/Conditional status', 'commissioning PDF'], provenance: 'tracking' },
    { id: 'cx.testsTotal', label: 'Cx Tests (screening)', group: 'Reliability & Cx', pages: ['commissioning'], sourceParams: ['sim.itLoad', 'req.avgRackDensityKw'], formula: 'equipScale counts × tests-per-unit table (swgr 12, gen 8, chiller 6, UPS 4…) — labeled screening; pass/fail derive from checklist ticks when in use', engineFn: 'models.commissioning.equipScale', consumers: ['tests KPI', 'by-system table'], provenance: 'screening' },
    { id: 'evm.spiCpi', label: 'SPI / CPI', group: 'Reliability & Cx', pages: ['construction', 'finance', 'report'], sourceParams: ['constructionTracking.phaseActualPct', 'constructionTracking.acSpentUsd', 'capex.timeline'], formula: 'EV=Σ actual%×weight×budget; SPI=EV/PV, CPI=EV/AC — computed ONCE in the construction adapter; Financial and Results consume it as PASSTHROUGH (never recomputed); Plan Mode → 1.00', engineFn: 'construction-adapter.evm', consumers: ['Financial forecast-at-completion', 'Results construction score'], provenance: 'tracking', notes: 'Single-source rule: one EVM, three consumers.' },

    /* ═══ 5 · SITE & SIBLING ENGINES ═══ */
    { id: 'site.score', label: 'Site Total Score', group: 'Site & siblings', pages: ['site', 'report', 'dashboard'], sourceParams: ['sites.attributes', 'sim.country'], formula: 'models.site.deriveFactors(countryId, attribute overrides) → models.site.score — ENGINE authoritative; a no-override site reproduces the country score exactly (parity invariant)', engineFn: 'models.site.score', consumers: ['radar Site Score axis', 'Results site dimension', 'ranking'], provenance: 'engine' },
    { id: 'site.ctx', label: 'Site Analyses Context', group: 'Site & siblings', pages: ['site'], sourceParams: ['sim.itLoad', 'capex.total', 'staff.headcounts', 'sim.country'], formula: 'revenue = DATA.decision.revenuePerKwMonth (≈$280) × itLoad × 12 (screening); FTE = Σ headcounts; staffCost = FTE × country engineer salary × 1.3 burden; life 15y @10% discount; equipment share 0.6', consumers: ['tax/disaster/grid/talent/compliance per-site runs'], provenance: 'screening' },
    { id: 'site.grid', label: 'Grid Reliability (per site)', group: 'Site & siblings', pages: ['site', 'grid'], sourceParams: ['site.countryId', 'sim.itLoad', 'sim.tierLevel', 'sim.coolingType'], formula: 'Same engine as the Grid deep-dive tab — score/grade, outages/yr, outage minutes, required gen MW, fuel cost', engineFn: 'calculateGridReliability', consumers: ['integrated panel', 'radar Grid axis', 'comparison rows'], provenance: 'engine' },
    { id: 'site.disaster', label: 'Disaster Risk (per site)', group: 'Site & siblings', pages: ['site', 'disaster'], sourceParams: ['site.countryId', 'capex.total', 'sim.itLoad', 'site.ctx'], formula: 'Composite score, insurance $/yr, expected annual loss, BI days, revenue at risk — same engine as the Disaster tab', engineFn: 'calculateDisasterRisk', consumers: ['integrated panel', 'radar Disaster-Safety axis (100−score)', 'comparison'], provenance: 'engine' },
    { id: 'site.tax', label: 'Tax Incentives (per site)', group: 'Site & siblings', pages: ['site', 'tax'], sourceParams: ['site.countryId', 'capex.total', 'site.ctx'], formula: '15-year incentive value, FTZ, NPV with/without, IRR, country rank — same engine as the Tax tab', engineFn: 'calculateTaxIncentives', consumers: ['integrated panel', 'radar Tax axis', 'comparison'], provenance: 'engine' },
    { id: 'site.talent', label: 'Talent (per site)', group: 'Site & siblings', pages: ['site', 'talent'], sourceParams: ['site.countryId', 'site.ctx'], formula: 'Talent score, hiring difficulty, time-to-full-staff, recruitment cost — same engine as the Talent tab', engineFn: 'calculateTalentAvailability', consumers: ['integrated panel', 'radar Talent axis'], provenance: 'engine' },
    { id: 'site.compliance', label: 'Compliance (per site)', group: 'Site & siblings', pages: ['site', 'compliance'], sourceParams: ['site.countryId', 'sim.itLoad'], formula: 'Compliance score, mandatory items, initial + annual cost — same engine as the Compliance tab', engineFn: 'calculateCompliance', consumers: ['integrated panel', 'radar Compliance axis'], provenance: 'engine' },

    /* ═══ 6 · STAFF / ASSETS / SPARES ═══ */
    { id: 'staff.headcounts', label: 'Headcounts (5 roles)', group: 'Staff & assets', pages: ['sim', 'staff', 'ops', 'site', 'finance'], sourceParams: ['sim.headcount_*'], formula: 'Auto from the staffing model (MW-scaled) or manual override; ONE store field family consumed everywhere', engineFn: 'calculateStaffing / ShiftEngine', consumers: ['monthly payroll', 'opex staffing line', 'site talent ctx FTE', 'ops on-shift count'], provenance: 'input' },
    { id: 'asset.fleet', label: 'Asset Fleet Counts', group: 'Staff & assets', pages: ['assets', 'spares', 'reliability', 'commissioning', 'architecture'], sourceParams: ['sim.itLoad', 'req.avgRackDensityKw'], formula: 'equipScale(itLoad, density bucket): swgr=⌈kW/5000⌉+1, UPS=⌈kW/500⌉, gen=⌈kW/2000⌉, chillers=⌈kW/500⌉, PDU=⌈kW/100⌉ … — the SAME fleet on five pages', engineFn: 'models.commissioning.equipScale', consumers: ['asset health rows', 'spares demand', 'reliability component counts', 'cx tests', 'diagram unit badges'], provenance: 'engine', notes: 'One scaling function; any two pages disagreeing on a unit count is a bug.' },
    { id: 'asset.health', label: 'Asset Health /100', group: 'Staff & assets', pages: ['assets'], sourceParams: ['asset.fleet', 'assets.ageYears', 'assets.condition'], formula: 'Engine Weibull healthIndex(class, age, condition, duty) per class — planning-model health, not telemetry', engineFn: 'models.asset.healthIndex', consumers: ['health buckets', 'at-risk count'], provenance: 'engine' },
    { id: 'spares.qstar', label: 'Spares Q* / ROP', group: 'Staff & assets', pages: ['spares', 'maint'], sourceParams: ['asset.fleet', 'sim.country'], formula: 'demand/yr = fleet × 8760/MTBF (IEEE-493); newsvendor CR = Cu/(Cu+Co) → Q*, ROP, safety stock, fill; lead weeks from the country table; Poisson mode auto at low demand', engineFn: 'models.spares.newsvendor', consumers: ['stock value KPI', 'per-class table', 'maintenance spares view'], provenance: 'engine' },

    /* ═══ 7 · FINANCIAL & RESULTS ═══ */
    { id: 'fin.budgetBaseline', label: 'Budget Baseline', group: 'Financial & results', pages: ['finance'], sourceParams: ['capex.total', 'financialTracking.revisions'], formula: 'capex.total + Σ approved revisions (fractions × baseline)', consumers: ['variance', 'forecast at completion'], provenance: 'derived' },
    { id: 'fin.opexYtd', label: 'OPEX YTD', group: 'Financial & results', pages: ['finance'], sourceParams: ['opex.totalAnnual'], formula: 'totalAnnual ÷ 12 × months since COD; donut = engine field map (power/staffing/maintenance/contract/insurance/others)', consumers: ['opex donut', 'insights'], provenance: 'derived' },
    { id: 'invest.structure', label: 'Debt / Equity Split', group: 'Financial & results', pages: ['invest'], sourceParams: ['capex.total', 'invest.debtRatio'], formula: 'capex.total × debtRatio (default 65%) → amortization schedule, DSCR, equity IRR', engineFn: 'InvestmentEngine.calculateInvestment', consumers: ['waterfall', 'Results financial outcomes'], provenance: 'derived' },
    { id: 'results.overall', label: 'Results Overall Score', group: 'Financial & results', pages: ['report', 'dashboard'], sourceParams: ['ALL sibling adapters'], formula: 'Weighted composite of 8 documented dimension scores (req completeness 12%, site 13%, arch 12%, capex-vs-band 13%, construction SPI/CPI 12%, ops 12%, sustainability 13%, financial IRR-vs-hurdle 13%)', consumers: ['grade', 'executive verdict'], provenance: 'derived', notes: 'Every dimension basis printed on the page and in the PDF.' },
    { id: 'compare.score', label: 'Scenario Comparison Score', group: 'Financial & results', pages: ['scenario-compare'], sourceParams: ['scenario.summary.*'], formula: 'Normalized within the chosen set: cost 35% (capex+opex, lower better) + efficiency 25% (PUE) + financial 25% (IRR) + carbon 15% (CO₂) → grade A-D', consumers: ['score summary', 'insights'], provenance: 'derived' },
];

export const BINDING_GROUPS = [...new Set(VALUE_BINDINGS.map((b) => b.group))];

export function bindingsFor(page: string): ValueBinding[] {
    return VALUE_BINDINGS.filter((b) => b.pages.includes(page));
}
