#!/usr/bin/env node
/* dc-corpus aggregate — turns dc-facts.json into per-metric×segment
 * distributions and writes them into the ENGINE as DATA.benchmarksCorpus
 * (between @@CORPUS_START/@@CORPUS_END markers — generated, never hand-edited;
 * same pattern as DATA.countries). Auto-link chain: after this, run terser +
 * build-engine-catalog + test-value-bindings. */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const DIR = dirname(fileURLToPath(import.meta.url));
const ENGINE = join(DIR, '..', '..', 'rz-engine.js');
const { facts } = JSON.parse(readFileSync(join(DIR, 'dc-facts.json'), 'utf8'));

const pct = (sorted, p) => sorted[Math.min(sorted.length - 1, Math.floor(p * sorted.length))];
const groups = {};
for (const f of facts) {
    const k = `${f.metric}|${f.segment}`;
    (groups[k] ??= []).push(f);
}
const out = {};
for (const [k, arr] of Object.entries(groups).sort()) {
    const [metric, segment] = k.split('|');
    const vals = arr.map((x) => x.value).sort((a, b) => a - b);
    if (vals.length < 3) continue;                      // need a real distribution
    (out[metric] ??= {})[segment] = {
        n: vals.length,
        unit: arr[0].unit,
        p10: pct(vals, 0.10), p25: pct(vals, 0.25), p50: pct(vals, 0.50),
        p75: pct(vals, 0.75), p90: pct(vals, 0.90),
        companies: [...new Set(arr.map((x) => x.company))].sort(),
        sources: [...new Set(arr.map((x) => x.source_url))].length,
    };
}

const block = `/* @@CORPUS_START — GENERATED by tools/dc-corpus/aggregate.mjs from dc-facts.json
 * (public multi-source corpus; every underlying fact carries source_url + verbatim
 * quote, gate-enforced). Do NOT hand-edit — rerun the corpus pipeline. */
        benchmarksCorpus: ${JSON.stringify(out, null, 8).replace(/\n/g, '\n        ')},
        /* @@CORPUS_END */`;

let s = readFileSync(ENGINE, 'utf8');
if (s.includes('@@CORPUS_START')) {
    s = s.replace(/\/\* @@CORPUS_START[\s\S]*?@@CORPUS_END \*\//, block);
} else {
    const anchor = '        /* ── A1: operations-maturity assessment (promoted from article-1). ── */';
    if (!s.includes(anchor)) throw new Error('engine anchor not found');
    s = s.replace(anchor, block + '\n\n' + anchor);
}
/* DATA.sources entry */
if (!s.includes("'benchmarksCorpus':")) {
    const srcAnchor = "            'opsMaturity':            { source:";
    s = s.replace(srcAnchor, `            'benchmarksCorpus':       { source: 'DC public-data corpus (tools/dc-corpus): operator/hyperscaler sustainability & annual reports + research bodies — every fact carries source_url + verbatim quote; distributions p10-p90 per metric x segment', asOf: '2026-07-19', method: 'markitdown ingestion + heuristic extraction + percentile aggregation; regenerate via the corpus pipeline (append-only)' },\n` + srcAnchor);
}
writeFileSync(ENGINE, s);

/* EA6b — Research Library doc list for the Knowledge Base (auto-generated) */
const docs = {};
for (const f of facts) {
    (docs[f.source_url] ??= { url: f.source_url, company: f.company, segment: f.segment, factCount: 0, metrics: new Set() });
    docs[f.source_url].factCount++;
    docs[f.source_url].metrics.add(f.metric);
}
const research = Object.values(docs).map((d) => ({ ...d, metrics: [...d.metrics].sort() }))
    .sort((a, b) => b.factCount - a.factCount);
writeFileSync(join(DIR, '..', '..', 'dcmoc', 'src', 'lib', 'research-library.json'),
    JSON.stringify({ generated: '2026-07-19', note: 'AUTO-GENERATED doc index of the DC public-data corpus — regenerate via the corpus pipeline.', docs: research }, null, 1) + '\n');
/* Arc-2 (2026-07-20): corpus-facts.json — slim per-fact mirror for the Data Library
 * drill-down (was a manual agent step; now deterministic pipeline output).
 * Sort stabil (metric → segment → company → value) + quote dipotong 240 char. */
const slim = facts.map((f) => ({
    metric: f.metric, value: f.value, unit: f.unit, company: f.company,
    segment: f.segment, year: f.year ?? null, source_url: f.source_url,
    quote: String(f.quote ?? '').slice(0, 240),
})).sort((a, b) =>
    a.metric.localeCompare(b.metric) || a.segment.localeCompare(b.segment)
    || a.company.localeCompare(b.company) || a.value - b.value);
writeFileSync(join(DIR, '..', '..', 'dcmoc', 'src', 'lib', 'corpus-facts.json'),
    JSON.stringify({ note: 'AUTO-GENERATED slim fact mirror of dc-facts.json — regenerate via the corpus pipeline.', facts: slim }, null, 1) + '\n');
console.log('AGGREGATE →', Object.keys(out).map((m) => `${m}(${Object.keys(out[m]).join(',')})`).join(' · '), `· research docs: ${research.length} · slim facts: ${slim.length}`);
