/* ─── LAYER 13 · AI DECISION ENGINE — TYPES ──────────────────────────────────
 * The typed contract for the DC-OS decision layer. A deterministic rule engine
 * implements `DecisionProvider` NOW (no LLM); a future real-AI backend can be
 * plugged in behind the SAME interface (see remoteApiProvider) with zero caller
 * changes — this is the "container / wadah" for an AI API the platform requires.
 *
 * The provider reads a normalized snapshot of every engine's headline outputs
 * (DecisionContext) + the user's constraints/objectives, and returns an
 * explainable recommendation with a rationale trace. Nothing here is investment
 * advice — recommendations are engineering/feasibility guidance only.
 * ──────────────────────────────────────────────────────────────────────────── */

export type EngineId =
    | 'requirements' | 'site' | 'architecture' | 'capacity' | 'capex'
    | 'construction' | 'commissioning' | 'operations' | 'asset' | 'reliability'
    | 'sustainability' | 'financial' | 'decision';

export type Tier = 2 | 3 | 4;

/** Normalized headline outputs from the engines — the digital-thread snapshot. */
export interface DecisionContext {
    inputs: {
        itLoadKw: number;
        tier: Tier;
        coolingType: string;
        region: string;
        redundancy?: string;
    };
    capex?: { totalUsd: number; perKw?: number; timelineMonths?: number };
    opex?: { annualUsd: number };
    financial?: { npvUsd?: number; irrPct?: number; paybackYears?: number; roiPct?: number };
    carbon?: { annualTonnes?: number; pue?: number };
    reliability?: { availabilityPct?: number };
    site?: { score?: number };
    capacity?: { totalMw?: number };
}

/** Hard/soft constraints the recommender must respect. */
export interface DecisionConstraints {
    budgetUsd?: number;
    targetTier?: Tier;
    deadlineMonths?: number;
    region?: string;
    maxPue?: number;
    minAvailabilityPct?: number;
}

export type Objective = 'minCost' | 'minCarbon' | 'maxReliability' | 'fastestDelivery' | 'maxRoi';

export interface DecisionRequest {
    context: DecisionContext;
    constraints?: DecisionConstraints;
    objectives?: Objective[];
}

/** One explainable step: an engine value → a rule → a conclusion. */
export interface RationaleStep {
    engine: EngineId | 'multi';
    observation: string;   // e.g. "Tier IV CAPEX ≈ $58M exceeds the $30M budget"
    rule: string;          // e.g. "budget < tierCapex → downgrade tier"
    conclusion: string;    // e.g. "Tier III+ recommended"
    severity: 'info' | 'warn' | 'critical';
}

export interface DecisionRecommendation {
    title: string;
    detail: string;
    confidence: number;    // 0..1
    tags: string[];
}

export interface DecisionResult {
    summary: string;                       // one-line headline recommendation
    recommendations: DecisionRecommendation[];
    rationale: RationaleStep[];
    metrics: { feasible: boolean; roiYears?: number; confidence: number };
    provider: 'deterministic' | 'remoteApi';
    generatedFor: { itLoadKw: number; tier: Tier; region: string };
    disclaimer: string;
}

/** The pluggable seam. deterministicProvider now; remoteApiProvider (AI) later. */
export interface DecisionProvider {
    readonly id: 'deterministic' | 'remoteApi';
    decide(req: DecisionRequest): Promise<DecisionResult>;
}

export const DECISION_DISCLAIMER =
    'Engineering feasibility guidance generated by a deterministic rule engine ' +
    'from your engine outputs — not investment, legal, or professional advice. ' +
    'Validate against a full design review.';
