export interface OvertimeRules {
    workday: {
        firstHour: number;
        subsequent: number;
    };
    holiday: {
        first8Hours: number;
        ninthHour: number;
        tenthHourPlus: number;
    };
    maxOvertimeHoursPerWeek?: number;
}

export interface CountryProfile {
    id: string;
    region: 'APAC' | 'EMEA' | 'AMER' | 'MENA' | 'AFR' | 'LATAM';
    name: string;
    currency: string;
    currencySymbol: string;
    economy: {
        inflationRate: number; // General CPI (Parts/Consumables)
        laborEscalation: number; // Annual Wage Growth
        taxRate: number; // Corporate tax rate (decimal, e.g. 0.22 for 22%)
        electricityRate: number; // $/kWh grid electricity cost
    };
    constructionIndex?: number; // Relative to US (1.0) for CAPEX
    labor: {
        minimumWage: number;
        baseSalary_ShiftLead: number;
        baseSalary_Engineer: number;
        baseSalary_Technician: number;
        baseSalary_Admin: number;
        baseSalary_Janitor: number;
        laborRatePerHour: number; // Internal technician $/hr for maintenance
        overtimeRules: OvertimeRules;
        shrinkageFactor: number;
        leaves: {
            annual: number;
            publicHolidays: number;
            sickAverage: number;
        };
    };
    compliance: {
        certifications: string[];
        annualComplianceCost: number;
    };
    environment: {
        baselineAQI: number;
        gridCarbonIntensity: number;
    };
    risk: {
        downtimeCostPerMin: number; // $/min downtime cost (country-adjusted)
    };
    supplyChain: {
        importDifficultyFactor: number;
    };
    taxIncentives?: {
        freeTradeZones: string[];
        taxHolidayYears: number;
        taxHolidayRate: number;
        incentivePrograms: string[];
        importDutyExemption: boolean;
        landSubsidy: boolean;
        effectiveTaxRate: number;
    };
    naturalDisaster?: {
        seismicZone: 0 | 1 | 2 | 3 | 4;
        floodRisk: 'low' | 'moderate' | 'high' | 'extreme';
        typhoonRisk: 'none' | 'low' | 'moderate' | 'high';
        volcanoRisk: 'none' | 'low' | 'moderate';
        tsunamiRisk: 'none' | 'low' | 'moderate' | 'high';
        compositeScore: number;
        insuranceMultiplier: number;
        structuralReinforcement: number;
    };
    gridReliability?: {
        gridUptime: number;
        voltageStability: 'stable' | 'moderate' | 'unstable';
        brownoutFrequency: number;
        averageOutageDuration: number;
        gridTier: 1 | 2 | 3;
        backupFuelPremium: number;
        recommendedGenHours: number;
        renewableReadiness: number;
    };
    talentPool?: {
        dcEngineerPool: 'abundant' | 'moderate' | 'scarce' | 'very_scarce';
        universityPipeline: number;
        hyperscalerPresence: number;
        avgHiringDays: number;
        salaryPremium: number;
        talentScore: number;
        certifiedProfessionals: number;
    };
    fuelDiesel?: {
        dieselPricePerLiter: number;
        dieselAvailability: 'abundant' | 'moderate' | 'scarce';
        hvoAvailable: boolean;
        hvoPricePerLiter: number;
        fuelTaxRate: number;
        deliveryLeadDays: number;
        environmentalPermitRequired: boolean;
        storageLimitLiters: number;
        fuelQualityRating: 'high' | 'moderate' | 'low';
    };
    lastUpdated: string; // Data freshness indicator e.g. '2025-Q1'
}

export const COUNTRIES: Record<string, CountryProfile> = {
    ID: {
        id: 'ID',
        region: 'APAC',
        name: 'Indonesia',
        currency: 'USD',
        currencySymbol: '$',
        economy: {
            inflationRate: 0.035,
            laborEscalation: 0.05,
            taxRate: 0.22,
            electricityRate: 0.08,
        },
        labor: {
            minimumWage: 350,
            baseSalary_ShiftLead: 1500,
            baseSalary_Engineer: 1000,
            baseSalary_Technician: 550,
            baseSalary_Admin: 450,
            baseSalary_Janitor: 350,
            laborRatePerHour: 10,
            overtimeRules: {
                workday: { firstHour: 1.5, subsequent: 2.0 },
                holiday: { first8Hours: 2.0, ninthHour: 3.0, tenthHourPlus: 4.0 },
                maxOvertimeHoursPerWeek: 18,
            },
            shrinkageFactor: 0.20,
            leaves: { annual: 12, publicHolidays: 15, sickAverage: 5 },
        },
        compliance: {
            certifications: ['Sertifikat Laik Operasi (SLO)', 'Ahli K3 Listrik', 'AMDAL', 'PP 35/2021'],
            annualComplianceCost: 6500,
        },
        environment: {
            baselineAQI: 120,
            gridCarbonIntensity: 0.7,
        },
        risk: {
            downtimeCostPerMin: 1500,
        },
        supplyChain: {
            importDifficultyFactor: 1.35,
        },
        taxIncentives: {
            freeTradeZones: ['Batam FTZ', 'Nusantara Capital (IKN)', 'Cikarang SEZ'],
            taxHolidayYears: 10,
            taxHolidayRate: 0.0,
            incentivePrograms: ['Tax Holiday PP 40/2021', 'Super Deduction R&D', 'IKN Capital Incentive'],
            importDutyExemption: true,
            landSubsidy: true,
            effectiveTaxRate: 0.0,
        },
        naturalDisaster: {
            seismicZone: 3,
            floodRisk: 'high',
            typhoonRisk: 'none',
            volcanoRisk: 'moderate',
            tsunamiRisk: 'moderate',
            compositeScore: 68,
            insuranceMultiplier: 1.6,
            structuralReinforcement: 0.12,
        },
        gridReliability: {
            gridUptime: 99.5,
            voltageStability: 'moderate',
            brownoutFrequency: 18,
            averageOutageDuration: 45,
            gridTier: 2,
            backupFuelPremium: 0.15,
            recommendedGenHours: 72,
            renewableReadiness: 55,
        },
        talentPool: {
            dcEngineerPool: 'moderate',
            universityPipeline: 45,
            hyperscalerPresence: 4,
            avgHiringDays: 45,
            salaryPremium: 1.1,
            talentScore: 55,
            certifiedProfessionals: 320,
        },
        fuelDiesel: {
            dieselPricePerLiter: 0.95,
            dieselAvailability: 'abundant',
            hvoAvailable: false,
            hvoPricePerLiter: 0,
            fuelTaxRate: 0.05,
            deliveryLeadDays: 3,
            environmentalPermitRequired: true,
            storageLimitLiters: 50000,
            fuelQualityRating: 'moderate',
        },
        lastUpdated: '2025-Q1',
    },
    SG: {
        id: 'SG',
        region: 'APAC',
        name: 'Singapore',
        currency: 'SGD',
        currencySymbol: 'S$',
        economy: {
            inflationRate: 0.025,
            laborEscalation: 0.04,
            taxRate: 0.17,
            electricityRate: 0.15,
        },
        labor: {
            minimumWage: 1400,
            baseSalary_ShiftLead: 5500,
            baseSalary_Engineer: 4500,
            baseSalary_Technician: 3200,
            baseSalary_Admin: 2800,
            baseSalary_Janitor: 1800,
            laborRatePerHour: 35,
            overtimeRules: {
                workday: { firstHour: 1.5, subsequent: 1.5 },
                holiday: { first8Hours: 2.0, ninthHour: 2.0, tenthHourPlus: 2.0 },
            },
            shrinkageFactor: 0.12,
            leaves: { annual: 14, publicHolidays: 11, sickAverage: 4 },
        },
        compliance: {
            certifications: ['SS 564', 'BCA Green Mark'],
            annualComplianceCost: 12000,
        },
        environment: {
            baselineAQI: 45,
            gridCarbonIntensity: 0.4,
        },
        risk: {
            downtimeCostPerMin: 4500,
        },
        supplyChain: { importDifficultyFactor: 1.0 },
        taxIncentives: {
            freeTradeZones: ['Jurong Island', 'Changi Business Park'],
            taxHolidayYears: 5,
            taxHolidayRate: 0.05,
            incentivePrograms: ['Pioneer Certificate', 'Development & Expansion Incentive', 'Green DC Incentive'],
            importDutyExemption: true,
            landSubsidy: false,
            effectiveTaxRate: 0.05,
        },
        naturalDisaster: {
            seismicZone: 0,
            floodRisk: 'moderate',
            typhoonRisk: 'none',
            volcanoRisk: 'none',
            tsunamiRisk: 'low',
            compositeScore: 12,
            insuranceMultiplier: 1.0,
            structuralReinforcement: 0.0,
        },
        gridReliability: {
            gridUptime: 99.999,
            voltageStability: 'stable',
            brownoutFrequency: 0,
            averageOutageDuration: 1,
            gridTier: 1,
            backupFuelPremium: 0.0,
            recommendedGenHours: 24,
            renewableReadiness: 40,
        },
        talentPool: {
            dcEngineerPool: 'moderate',
            universityPipeline: 8,
            hyperscalerPresence: 8,
            avgHiringDays: 35,
            salaryPremium: 1.15,
            talentScore: 72,
            certifiedProfessionals: 850,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.55,
            dieselAvailability: 'abundant',
            hvoAvailable: true,
            hvoPricePerLiter: 2.80,
            fuelTaxRate: 0.10,
            deliveryLeadDays: 1,
            environmentalPermitRequired: true,
            storageLimitLiters: 30000,
            fuelQualityRating: 'high',
        },
        lastUpdated: '2025-Q1',
    },
    MY: {
        id: 'MY',
        region: 'APAC',
        name: 'Malaysia',
        currency: 'MYR',
        currencySymbol: 'RM',
        economy: {
            inflationRate: 0.03, // 3%
            laborEscalation: 0.045, // 4.5%
            taxRate: 0.24,
            electricityRate: 0.07,
        },
        labor: {
            minimumWage: 340,
            baseSalary_ShiftLead: 1800,
            baseSalary_Engineer: 1200,
            baseSalary_Technician: 700,
            baseSalary_Admin: 500,
            baseSalary_Janitor: 350,
            laborRatePerHour: 8,
            overtimeRules: {
                workday: { firstHour: 1.5, subsequent: 1.5 },
                holiday: { first8Hours: 2.0, ninthHour: 3.0, tenthHourPlus: 3.0 },
            },
            shrinkageFactor: 0.18,
            leaves: { annual: 12, publicHolidays: 16, sickAverage: 5 },
        },
        compliance: {
            certifications: ['Suruhanjaya Tenaga', 'GBI'],
            annualComplianceCost: 5000,
        },
        environment: {
            baselineAQI: 90,
            gridCarbonIntensity: 0.6,
        },
        risk: {
            downtimeCostPerMin: 1200,
        },
        supplyChain: { importDifficultyFactor: 1.1 },
        taxIncentives: {
            freeTradeZones: ['Iskandar Malaysia', 'Cyberjaya', 'Kulim Hi-Tech Park'],
            taxHolidayYears: 10,
            taxHolidayRate: 0.0,
            incentivePrograms: ['MSC Malaysia Status', 'Pioneer Status', 'Green Technology Tax Allowance'],
            importDutyExemption: true,
            landSubsidy: true,
            effectiveTaxRate: 0.0,
        },
        naturalDisaster: {
            seismicZone: 1,
            floodRisk: 'high',
            typhoonRisk: 'none',
            volcanoRisk: 'none',
            tsunamiRisk: 'low',
            compositeScore: 28,
            insuranceMultiplier: 1.15,
            structuralReinforcement: 0.02,
        },
        gridReliability: {
            gridUptime: 99.9,
            voltageStability: 'stable',
            brownoutFrequency: 4,
            averageOutageDuration: 20,
            gridTier: 1,
            backupFuelPremium: 0.05,
            recommendedGenHours: 48,
            renewableReadiness: 60,
        },
        talentPool: {
            dcEngineerPool: 'moderate',
            universityPipeline: 25,
            hyperscalerPresence: 5,
            avgHiringDays: 40,
            salaryPremium: 1.1,
            talentScore: 60,
            certifiedProfessionals: 420,
        },
        fuelDiesel: {
            dieselPricePerLiter: 0.55,
            dieselAvailability: 'abundant',
            hvoAvailable: false,
            hvoPricePerLiter: 0,
            fuelTaxRate: 0.0,
            deliveryLeadDays: 2,
            environmentalPermitRequired: true,
            storageLimitLiters: 50000,
            fuelQualityRating: 'moderate',
        },
        lastUpdated: '2025-Q1',
    },
    US: {
        id: 'US',
        region: 'AMER',
        name: 'United States',
        currency: 'USD',
        currencySymbol: '$',
        economy: {
            inflationRate: 0.03, // 3%
            laborEscalation: 0.035, // 3.5%
            taxRate: 0.21,
            electricityRate: 0.12,
        },
        labor: {
            minimumWage: 2000,
            baseSalary_ShiftLead: 10500,
            baseSalary_Engineer: 8500,
            baseSalary_Technician: 5500,
            baseSalary_Admin: 4000,
            baseSalary_Janitor: 3000,
            laborRatePerHour: 45,
            overtimeRules: {
                workday: { firstHour: 1.5, subsequent: 1.5 },
                holiday: { first8Hours: 1.5, ninthHour: 1.5, tenthHourPlus: 1.5 },
            },
            shrinkageFactor: 0.10,
            leaves: { annual: 10, publicHolidays: 10, sickAverage: 3 },
        },
        compliance: {
            certifications: ['OSHA', 'NFPA 70E'],
            annualComplianceCost: 15000,
        },
        environment: {
            baselineAQI: 35,
            gridCarbonIntensity: 0.4,
        },
        risk: {
            downtimeCostPerMin: 5000,
        },
        supplyChain: { importDifficultyFactor: 1.0 },
        taxIncentives: {
            freeTradeZones: ['Foreign Trade Zones (250+)'],
            taxHolidayYears: 0,
            taxHolidayRate: 0.21,
            incentivePrograms: ['ITC for Energy Property', 'Opportunity Zones', 'State-level DC Sales Tax Exemptions'],
            importDutyExemption: false,
            landSubsidy: false,
            effectiveTaxRate: 0.21,
        },
        naturalDisaster: {
            seismicZone: 2,
            floodRisk: 'moderate',
            typhoonRisk: 'moderate',
            volcanoRisk: 'low',
            tsunamiRisk: 'low',
            compositeScore: 38,
            insuranceMultiplier: 1.2,
            structuralReinforcement: 0.05,
        },
        gridReliability: {
            gridUptime: 99.97,
            voltageStability: 'stable',
            brownoutFrequency: 1,
            averageOutageDuration: 10,
            gridTier: 1,
            backupFuelPremium: 0.0,
            recommendedGenHours: 48,
            renewableReadiness: 70,
        },
        talentPool: {
            dcEngineerPool: 'abundant',
            universityPipeline: 120,
            hyperscalerPresence: 10,
            avgHiringDays: 30,
            salaryPremium: 1.0,
            talentScore: 90,
            certifiedProfessionals: 8500,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.05,
            dieselAvailability: 'abundant',
            hvoAvailable: true,
            hvoPricePerLiter: 2.20,
            fuelTaxRate: 0.06,
            deliveryLeadDays: 1,
            environmentalPermitRequired: true,
            storageLimitLiters: 100000,
            fuelQualityRating: 'high',
        },
        lastUpdated: '2025-Q1',
    },
    JP: {
        id: 'JP',
        region: 'APAC',
        name: 'Japan',
        currency: 'JPY',
        currencySymbol: '¥',
        economy: {
            inflationRate: 0.01, // 1%
            laborEscalation: 0.02, // 2%
            taxRate: 0.2304,
            electricityRate: 0.20,
        },
        labor: {
            minimumWage: 1200,
            baseSalary_ShiftLead: 4500,
            baseSalary_Engineer: 3500,
            baseSalary_Technician: 2800,
            baseSalary_Admin: 2200,
            baseSalary_Janitor: 1800,
            laborRatePerHour: 30,
            overtimeRules: {
                workday: { firstHour: 1.25, subsequent: 1.25 },
                holiday: { first8Hours: 1.35, ninthHour: 1.35, tenthHourPlus: 1.35 },
            },
            shrinkageFactor: 0.08,
            leaves: { annual: 10, publicHolidays: 16, sickAverage: 2 },
        },
        compliance: {
            certifications: ['First Class Electrician', 'Energy Manager'],
            annualComplianceCost: 8000,
        },
        environment: {
            baselineAQI: 30,
            gridCarbonIntensity: 0.5,
        },
        risk: {
            downtimeCostPerMin: 4000,
        },
        supplyChain: { importDifficultyFactor: 1.05 },
        taxIncentives: {
            freeTradeZones: ['Okinawa FTZ', 'Narita FTZ'],
            taxHolidayYears: 0,
            taxHolidayRate: 0.2304,
            incentivePrograms: ['J-Credits Scheme', 'Green Innovation Fund', 'Regional Revitalization Tax'],
            importDutyExemption: false,
            landSubsidy: false,
            effectiveTaxRate: 0.2304,
        },
        naturalDisaster: {
            seismicZone: 4,
            floodRisk: 'moderate',
            typhoonRisk: 'high',
            volcanoRisk: 'moderate',
            tsunamiRisk: 'high',
            compositeScore: 82,
            insuranceMultiplier: 1.8,
            structuralReinforcement: 0.18,
        },
        gridReliability: {
            gridUptime: 99.99,
            voltageStability: 'stable',
            brownoutFrequency: 0,
            averageOutageDuration: 5,
            gridTier: 1,
            backupFuelPremium: 0.0,
            recommendedGenHours: 48,
            renewableReadiness: 55,
        },
        talentPool: {
            dcEngineerPool: 'moderate',
            universityPipeline: 50,
            hyperscalerPresence: 7,
            avgHiringDays: 60,
            salaryPremium: 1.1,
            talentScore: 70,
            certifiedProfessionals: 1800,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.35,
            dieselAvailability: 'abundant',
            hvoAvailable: true,
            hvoPricePerLiter: 2.50,
            fuelTaxRate: 0.08,
            deliveryLeadDays: 1,
            environmentalPermitRequired: true,
            storageLimitLiters: 50000,
            fuelQualityRating: 'high',
        },
        lastUpdated: '2025-Q1',
    },
    AU: {
        id: 'AU',
        region: 'APAC',
        name: 'Australia',
        currency: 'AUD',
        currencySymbol: 'A$',
        economy: {
            inflationRate: 0.03, // 3%
            laborEscalation: 0.035, // 3.5%
            taxRate: 0.30,
            electricityRate: 0.18,
        },
        labor: {
            minimumWage: 3000,
            baseSalary_ShiftLead: 9500,
            baseSalary_Engineer: 8000,
            baseSalary_Technician: 6000,
            baseSalary_Admin: 5000,
            baseSalary_Janitor: 4000,
            laborRatePerHour: 40,
            overtimeRules: {
                workday: { firstHour: 1.5, subsequent: 2.0 },
                holiday: { first8Hours: 2.5, ninthHour: 2.5, tenthHourPlus: 2.5 },
            },
            shrinkageFactor: 0.12,
            leaves: { annual: 20, publicHolidays: 10, sickAverage: 5 },
        },
        compliance: {
            certifications: ['WHS', 'Austel'],
            annualComplianceCost: 10000,
        },
        environment: {
            baselineAQI: 20,
            gridCarbonIntensity: 0.6,
        },
        risk: {
            downtimeCostPerMin: 4500,
        },
        supplyChain: { importDifficultyFactor: 1.2 },
        taxIncentives: {
            freeTradeZones: ['Sydney Olympic Park'],
            taxHolidayYears: 0,
            taxHolidayRate: 0.30,
            incentivePrograms: ['R&D Tax Incentive', 'Clean Energy Finance Corp', 'NSW Digital Economy'],
            importDutyExemption: false,
            landSubsidy: false,
            effectiveTaxRate: 0.30,
        },
        naturalDisaster: {
            seismicZone: 1,
            floodRisk: 'moderate',
            typhoonRisk: 'low',
            volcanoRisk: 'none',
            tsunamiRisk: 'low',
            compositeScore: 22,
            insuranceMultiplier: 1.1,
            structuralReinforcement: 0.02,
        },
        gridReliability: {
            gridUptime: 99.98,
            voltageStability: 'stable',
            brownoutFrequency: 1,
            averageOutageDuration: 8,
            gridTier: 1,
            backupFuelPremium: 0.0,
            recommendedGenHours: 48,
            renewableReadiness: 80,
        },
        talentPool: {
            dcEngineerPool: 'moderate',
            universityPipeline: 18,
            hyperscalerPresence: 6,
            avgHiringDays: 35,
            salaryPremium: 1.05,
            talentScore: 75,
            certifiedProfessionals: 1200,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.30,
            dieselAvailability: 'abundant',
            hvoAvailable: true,
            hvoPricePerLiter: 2.40,
            fuelTaxRate: 0.10,
            deliveryLeadDays: 2,
            environmentalPermitRequired: true,
            storageLimitLiters: 80000,
            fuelQualityRating: 'high',
        },
        lastUpdated: '2025-Q1',
    },
    // ─── MENA ───────────────────────────────────────────────
    AE: {
        id: 'AE', region: 'MENA', name: 'UAE', currency: 'USD', currencySymbol: '$',
        economy: { inflationRate: 0.025, laborEscalation: 0.03, taxRate: 0.0, electricityRate: 0.08 },
        labor: {
            minimumWage: 800, baseSalary_ShiftLead: 5000, baseSalary_Engineer: 4000,
            baseSalary_Technician: 2500, baseSalary_Admin: 2000, baseSalary_Janitor: 1200,
            laborRatePerHour: 25,
            overtimeRules: { workday: { firstHour: 1.25, subsequent: 1.5 }, holiday: { first8Hours: 1.5, ninthHour: 1.5, tenthHourPlus: 1.5 } },
            shrinkageFactor: 0.10, leaves: { annual: 30, publicHolidays: 10, sickAverage: 5 },
        },
        compliance: { certifications: ['DCDA', 'Estidama', 'Civil Defence'], annualComplianceCost: 15000 },
        environment: { baselineAQI: 100, gridCarbonIntensity: 0.45 },
        risk: { downtimeCostPerMin: 3500 },
        supplyChain: { importDifficultyFactor: 1.0 },
        taxIncentives: {
            freeTradeZones: ['JAFZA', 'DAFZA', 'Masdar City', 'ADGM'],
            taxHolidayYears: 50,
            taxHolidayRate: 0.0,
            incentivePrograms: ['Free Zone 0% Tax', 'Dubai Industrial Strategy', 'Abu Dhabi Investment Office'],
            importDutyExemption: true,
            landSubsidy: true,
            effectiveTaxRate: 0.0,
        },
        naturalDisaster: {
            seismicZone: 1,
            floodRisk: 'low',
            typhoonRisk: 'none',
            volcanoRisk: 'none',
            tsunamiRisk: 'none',
            compositeScore: 8,
            insuranceMultiplier: 1.0,
            structuralReinforcement: 0.0,
        },
        gridReliability: {
            gridUptime: 99.98,
            voltageStability: 'stable',
            brownoutFrequency: 1,
            averageOutageDuration: 5,
            gridTier: 1,
            backupFuelPremium: 0.0,
            recommendedGenHours: 24,
            renewableReadiness: 75,
        },
        talentPool: {
            dcEngineerPool: 'moderate',
            universityPipeline: 6,
            hyperscalerPresence: 6,
            avgHiringDays: 30,
            salaryPremium: 1.15,
            talentScore: 65,
            certifiedProfessionals: 600,
        },
        fuelDiesel: {
            dieselPricePerLiter: 0.65,
            dieselAvailability: 'abundant',
            hvoAvailable: false,
            hvoPricePerLiter: 0,
            fuelTaxRate: 0.0,
            deliveryLeadDays: 1,
            environmentalPermitRequired: false,
            storageLimitLiters: 100000,
            fuelQualityRating: 'high',
        },
        lastUpdated: '2025-Q1',
    },
    SA: {
        id: 'SA', region: 'MENA', name: 'Saudi Arabia', currency: 'SAR', currencySymbol: '﷼',
        economy: { inflationRate: 0.02, laborEscalation: 0.035, taxRate: 0.20, electricityRate: 0.05 },
        labor: {
            minimumWage: 1100, baseSalary_ShiftLead: 4500, baseSalary_Engineer: 3800,
            baseSalary_Technician: 2200, baseSalary_Admin: 1800, baseSalary_Janitor: 1000,
            laborRatePerHour: 22,
            overtimeRules: { workday: { firstHour: 1.5, subsequent: 1.5 }, holiday: { first8Hours: 2.0, ninthHour: 2.0, tenthHourPlus: 2.0 } },
            shrinkageFactor: 0.12, leaves: { annual: 21, publicHolidays: 9, sickAverage: 4 },
        },
        compliance: { certifications: ['Saudi CDC', 'SASO', 'NEOM Standards'], annualComplianceCost: 12000 },
        environment: { baselineAQI: 110, gridCarbonIntensity: 0.55 },
        risk: { downtimeCostPerMin: 3000 },
        supplyChain: { importDifficultyFactor: 1.05 },
        taxIncentives: {
            freeTradeZones: ['KAEC', 'NEOM', 'Jazan Economic City'],
            taxHolidayYears: 10,
            taxHolidayRate: 0.0,
            incentivePrograms: ['Vision 2030 DC Initiative', 'SAGIA Investment License', 'NEOM Tech Incentive'],
            importDutyExemption: true,
            landSubsidy: true,
            effectiveTaxRate: 0.0,
        },
        naturalDisaster: {
            seismicZone: 1,
            floodRisk: 'low',
            typhoonRisk: 'none',
            volcanoRisk: 'low',
            tsunamiRisk: 'none',
            compositeScore: 10,
            insuranceMultiplier: 1.0,
            structuralReinforcement: 0.01,
        },
        gridReliability: {
            gridUptime: 99.95,
            voltageStability: 'stable',
            brownoutFrequency: 2,
            averageOutageDuration: 10,
            gridTier: 1,
            backupFuelPremium: 0.0,
            recommendedGenHours: 24,
            renewableReadiness: 80,
        },
        talentPool: {
            dcEngineerPool: 'scarce',
            universityPipeline: 8,
            hyperscalerPresence: 3,
            avgHiringDays: 50,
            salaryPremium: 1.2,
            talentScore: 45,
            certifiedProfessionals: 280,
        },
        fuelDiesel: {
            dieselPricePerLiter: 0.20,
            dieselAvailability: 'abundant',
            hvoAvailable: false,
            hvoPricePerLiter: 0,
            fuelTaxRate: 0.0,
            deliveryLeadDays: 1,
            environmentalPermitRequired: false,
            storageLimitLiters: 100000,
            fuelQualityRating: 'high',
        },
        lastUpdated: '2025-Q1',
    },
    QA: {
        id: 'QA', region: 'MENA', name: 'Qatar', currency: 'QAR', currencySymbol: 'QR',
        economy: { inflationRate: 0.02, laborEscalation: 0.03, taxRate: 0.10, electricityRate: 0.04 },
        labor: {
            minimumWage: 1000, baseSalary_ShiftLead: 5200, baseSalary_Engineer: 4200,
            baseSalary_Technician: 2600, baseSalary_Admin: 2100, baseSalary_Janitor: 1300,
            laborRatePerHour: 24,
            overtimeRules: { workday: { firstHour: 1.25, subsequent: 1.5 }, holiday: { first8Hours: 1.5, ninthHour: 1.5, tenthHourPlus: 1.5 } },
            shrinkageFactor: 0.10, leaves: { annual: 21, publicHolidays: 9, sickAverage: 4 },
        },
        compliance: { certifications: ['Kahramaa', 'QCS 2014'], annualComplianceCost: 14000 },
        environment: { baselineAQI: 95, gridCarbonIntensity: 0.48 },
        risk: { downtimeCostPerMin: 3500 },
        supplyChain: { importDifficultyFactor: 1.05 },
        taxIncentives: {
            freeTradeZones: ['Qatar Free Zones (QFZ)', 'Manateq Logistics Park'],
            taxHolidayYears: 20,
            taxHolidayRate: 0.0,
            incentivePrograms: ['QFZ 0% Tax', 'Qatar Investment Authority Support', 'Smart Qatar Programme'],
            importDutyExemption: true,
            landSubsidy: true,
            effectiveTaxRate: 0.0,
        },
        naturalDisaster: {
            seismicZone: 0,
            floodRisk: 'low',
            typhoonRisk: 'none',
            volcanoRisk: 'none',
            tsunamiRisk: 'none',
            compositeScore: 5,
            insuranceMultiplier: 1.0,
            structuralReinforcement: 0.0,
        },
        gridReliability: {
            gridUptime: 99.97,
            voltageStability: 'stable',
            brownoutFrequency: 1,
            averageOutageDuration: 8,
            gridTier: 1,
            backupFuelPremium: 0.0,
            recommendedGenHours: 24,
            renewableReadiness: 70,
        },
        talentPool: {
            dcEngineerPool: 'scarce',
            universityPipeline: 3,
            hyperscalerPresence: 2,
            avgHiringDays: 55,
            salaryPremium: 1.25,
            talentScore: 38,
            certifiedProfessionals: 120,
        },
        fuelDiesel: {
            dieselPricePerLiter: 0.30,
            dieselAvailability: 'abundant',
            hvoAvailable: false,
            hvoPricePerLiter: 0,
            fuelTaxRate: 0.0,
            deliveryLeadDays: 1,
            environmentalPermitRequired: false,
            storageLimitLiters: 80000,
            fuelQualityRating: 'high',
        },
        lastUpdated: '2025-Q1',
    },
    // ─── AFRICA ─────────────────────────────────────────────
    ZA: {
        id: 'ZA', region: 'AFR', name: 'South Africa', currency: 'ZAR', currencySymbol: 'R',
        economy: { inflationRate: 0.05, laborEscalation: 0.06, taxRate: 0.27, electricityRate: 0.10 },
        labor: {
            minimumWage: 250, baseSalary_ShiftLead: 2200, baseSalary_Engineer: 1800,
            baseSalary_Technician: 1100, baseSalary_Admin: 800, baseSalary_Janitor: 400,
            laborRatePerHour: 12,
            overtimeRules: { workday: { firstHour: 1.5, subsequent: 2.0 }, holiday: { first8Hours: 2.0, ninthHour: 2.0, tenthHourPlus: 2.0 } },
            shrinkageFactor: 0.22, leaves: { annual: 15, publicHolidays: 12, sickAverage: 6 },
        },
        compliance: { certifications: ['SABS', 'ECSA', 'OHS Act'], annualComplianceCost: 5000 },
        environment: { baselineAQI: 50, gridCarbonIntensity: 0.9 },
        risk: { downtimeCostPerMin: 1500 },
        supplyChain: { importDifficultyFactor: 1.3 },
        taxIncentives: {
            freeTradeZones: ['Coega IDZ', 'Dube TradePort', 'Richards Bay IDZ'],
            taxHolidayYears: 0,
            taxHolidayRate: 0.27,
            incentivePrograms: ['Section 12L Energy Efficiency', 'SEZ Tax Incentive (15%)', 'Renewable Energy Tax Deduction'],
            importDutyExemption: false,
            landSubsidy: false,
            effectiveTaxRate: 0.15,
        },
        naturalDisaster: {
            seismicZone: 1,
            floodRisk: 'moderate',
            typhoonRisk: 'none',
            volcanoRisk: 'none',
            tsunamiRisk: 'none',
            compositeScore: 15,
            insuranceMultiplier: 1.05,
            structuralReinforcement: 0.01,
        },
        gridReliability: {
            gridUptime: 95.0,
            voltageStability: 'unstable',
            brownoutFrequency: 200,
            averageOutageDuration: 120,
            gridTier: 3,
            backupFuelPremium: 0.40,
            recommendedGenHours: 168,
            renewableReadiness: 75,
        },
        talentPool: {
            dcEngineerPool: 'moderate',
            universityPipeline: 15,
            hyperscalerPresence: 4,
            avgHiringDays: 35,
            salaryPremium: 1.05,
            talentScore: 60,
            certifiedProfessionals: 450,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.15,
            dieselAvailability: 'moderate',
            hvoAvailable: false,
            hvoPricePerLiter: 0,
            fuelTaxRate: 0.07,
            deliveryLeadDays: 3,
            environmentalPermitRequired: true,
            storageLimitLiters: 60000,
            fuelQualityRating: 'moderate',
        },
        lastUpdated: '2025-Q1',
    },
    NG: {
        id: 'NG', region: 'AFR', name: 'Nigeria', currency: 'USD', currencySymbol: '$',
        economy: { inflationRate: 0.14, laborEscalation: 0.08, taxRate: 0.30, electricityRate: 0.12 },
        labor: {
            minimumWage: 80, baseSalary_ShiftLead: 1200, baseSalary_Engineer: 900,
            baseSalary_Technician: 500, baseSalary_Admin: 350, baseSalary_Janitor: 150,
            laborRatePerHour: 6,
            overtimeRules: { workday: { firstHour: 1.5, subsequent: 2.0 }, holiday: { first8Hours: 2.0, ninthHour: 2.0, tenthHourPlus: 2.0 } },
            shrinkageFactor: 0.25, leaves: { annual: 12, publicHolidays: 11, sickAverage: 5 },
        },
        compliance: { certifications: ['NCC', 'SON', 'NESREA'], annualComplianceCost: 3000 },
        environment: { baselineAQI: 140, gridCarbonIntensity: 0.45 },
        risk: { downtimeCostPerMin: 800 },
        supplyChain: { importDifficultyFactor: 1.6 },
        taxIncentives: {
            freeTradeZones: ['Lekki Free Zone', 'Calabar FTZ', 'Kano FTZ'],
            taxHolidayYears: 5,
            taxHolidayRate: 0.0,
            incentivePrograms: ['Pioneer Status Tax Holiday', 'Export Expansion Grant', 'Infrastructure Tax Relief'],
            importDutyExemption: true,
            landSubsidy: false,
            effectiveTaxRate: 0.0,
        },
        naturalDisaster: {
            seismicZone: 0,
            floodRisk: 'high',
            typhoonRisk: 'none',
            volcanoRisk: 'none',
            tsunamiRisk: 'none',
            compositeScore: 20,
            insuranceMultiplier: 1.15,
            structuralReinforcement: 0.01,
        },
        gridReliability: {
            gridUptime: 50.0,
            voltageStability: 'unstable',
            brownoutFrequency: 500,
            averageOutageDuration: 180,
            gridTier: 3,
            backupFuelPremium: 0.80,
            recommendedGenHours: 336,
            renewableReadiness: 65,
        },
        talentPool: {
            dcEngineerPool: 'very_scarce',
            universityPipeline: 10,
            hyperscalerPresence: 2,
            avgHiringDays: 75,
            salaryPremium: 1.3,
            talentScore: 25,
            certifiedProfessionals: 60,
        },
        fuelDiesel: {
            dieselPricePerLiter: 0.90,
            dieselAvailability: 'scarce',
            hvoAvailable: false,
            hvoPricePerLiter: 0,
            fuelTaxRate: 0.02,
            deliveryLeadDays: 7,
            environmentalPermitRequired: false,
            storageLimitLiters: 40000,
            fuelQualityRating: 'low',
        },
        lastUpdated: '2025-Q1',
    },
    KE: {
        id: 'KE', region: 'AFR', name: 'Kenya', currency: 'KES', currencySymbol: 'KSh',
        economy: { inflationRate: 0.07, laborEscalation: 0.06, taxRate: 0.30, electricityRate: 0.15 },
        labor: {
            minimumWage: 150, baseSalary_ShiftLead: 1400, baseSalary_Engineer: 1000,
            baseSalary_Technician: 600, baseSalary_Admin: 400, baseSalary_Janitor: 200,
            laborRatePerHour: 7,
            overtimeRules: { workday: { firstHour: 1.5, subsequent: 2.0 }, holiday: { first8Hours: 2.0, ninthHour: 2.0, tenthHourPlus: 2.0 } },
            shrinkageFactor: 0.20, leaves: { annual: 21, publicHolidays: 10, sickAverage: 5 },
        },
        compliance: { certifications: ['KEBS', 'ERC License'], annualComplianceCost: 3500 },
        environment: { baselineAQI: 60, gridCarbonIntensity: 0.3 },
        risk: { downtimeCostPerMin: 700 },
        supplyChain: { importDifficultyFactor: 1.5 },
        taxIncentives: {
            freeTradeZones: ['Nairobi SEZ', 'Konza Technopolis'],
            taxHolidayYears: 10,
            taxHolidayRate: 0.10,
            incentivePrograms: ['SEZ Corporate Tax 10%', 'Konza Silicon Savannah', 'Digital Economy Blueprint'],
            importDutyExemption: true,
            landSubsidy: true,
            effectiveTaxRate: 0.10,
        },
        naturalDisaster: {
            seismicZone: 2,
            floodRisk: 'moderate',
            typhoonRisk: 'none',
            volcanoRisk: 'low',
            tsunamiRisk: 'low',
            compositeScore: 25,
            insuranceMultiplier: 1.1,
            structuralReinforcement: 0.03,
        },
        gridReliability: {
            gridUptime: 85.0,
            voltageStability: 'unstable',
            brownoutFrequency: 120,
            averageOutageDuration: 90,
            gridTier: 3,
            backupFuelPremium: 0.50,
            recommendedGenHours: 168,
            renewableReadiness: 80,
        },
        talentPool: {
            dcEngineerPool: 'very_scarce',
            universityPipeline: 5,
            hyperscalerPresence: 3,
            avgHiringDays: 60,
            salaryPremium: 1.2,
            talentScore: 30,
            certifiedProfessionals: 80,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.25,
            dieselAvailability: 'moderate',
            hvoAvailable: false,
            hvoPricePerLiter: 0,
            fuelTaxRate: 0.08,
            deliveryLeadDays: 5,
            environmentalPermitRequired: true,
            storageLimitLiters: 40000,
            fuelQualityRating: 'moderate',
        },
        lastUpdated: '2025-Q1',
    },
    // ─── LATIN AMERICA ──────────────────────────────────────
    BR: {
        id: 'BR', region: 'LATAM', name: 'Brazil', currency: 'BRL', currencySymbol: 'R$',
        economy: { inflationRate: 0.045, laborEscalation: 0.05, taxRate: 0.34, electricityRate: 0.10 },
        labor: {
            minimumWage: 300, baseSalary_ShiftLead: 2000, baseSalary_Engineer: 1500,
            baseSalary_Technician: 900, baseSalary_Admin: 700, baseSalary_Janitor: 350,
            laborRatePerHour: 12,
            overtimeRules: { workday: { firstHour: 1.5, subsequent: 2.0 }, holiday: { first8Hours: 2.0, ninthHour: 2.0, tenthHourPlus: 2.0 } },
            shrinkageFactor: 0.22, leaves: { annual: 30, publicHolidays: 12, sickAverage: 5 },
        },
        compliance: { certifications: ['INMETRO', 'NR-10', 'ANATEL'], annualComplianceCost: 6000 },
        environment: { baselineAQI: 50, gridCarbonIntensity: 0.15 },
        risk: { downtimeCostPerMin: 1800 },
        supplyChain: { importDifficultyFactor: 1.4 },
        taxIncentives: {
            freeTradeZones: ['Manaus Free Zone', 'ZPE Export Processing Zones'],
            taxHolidayYears: 0,
            taxHolidayRate: 0.34,
            incentivePrograms: ['SUDENE/SUDAM Regional Incentive', 'Lei do Bem R&D', 'Manaus Digital Hub'],
            importDutyExemption: false,
            landSubsidy: false,
            effectiveTaxRate: 0.34,
        },
        naturalDisaster: {
            seismicZone: 0,
            floodRisk: 'high',
            typhoonRisk: 'none',
            volcanoRisk: 'none',
            tsunamiRisk: 'none',
            compositeScore: 18,
            insuranceMultiplier: 1.1,
            structuralReinforcement: 0.01,
        },
        gridReliability: {
            gridUptime: 99.8,
            voltageStability: 'moderate',
            brownoutFrequency: 8,
            averageOutageDuration: 30,
            gridTier: 2,
            backupFuelPremium: 0.08,
            recommendedGenHours: 48,
            renewableReadiness: 85,
        },
        talentPool: {
            dcEngineerPool: 'moderate',
            universityPipeline: 40,
            hyperscalerPresence: 5,
            avgHiringDays: 40,
            salaryPremium: 1.05,
            talentScore: 58,
            certifiedProfessionals: 350,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.10,
            dieselAvailability: 'abundant',
            hvoAvailable: false,
            hvoPricePerLiter: 0,
            fuelTaxRate: 0.12,
            deliveryLeadDays: 3,
            environmentalPermitRequired: true,
            storageLimitLiters: 60000,
            fuelQualityRating: 'moderate',
        },
        lastUpdated: '2025-Q1',
    },
    CL: {
        id: 'CL', region: 'LATAM', name: 'Chile', currency: 'CLP', currencySymbol: 'CL$',
        economy: { inflationRate: 0.04, laborEscalation: 0.04, taxRate: 0.27, electricityRate: 0.12 },
        labor: {
            minimumWage: 500, baseSalary_ShiftLead: 2300, baseSalary_Engineer: 1800,
            baseSalary_Technician: 1100, baseSalary_Admin: 800, baseSalary_Janitor: 500,
            laborRatePerHour: 14,
            overtimeRules: { workday: { firstHour: 1.5, subsequent: 1.5 }, holiday: { first8Hours: 2.0, ninthHour: 2.0, tenthHourPlus: 2.0 } },
            shrinkageFactor: 0.15, leaves: { annual: 15, publicHolidays: 15, sickAverage: 4 },
        },
        compliance: { certifications: ['SEC', 'INN Chile'], annualComplianceCost: 5000 },
        environment: { baselineAQI: 40, gridCarbonIntensity: 0.35 },
        risk: { downtimeCostPerMin: 1500 },
        supplyChain: { importDifficultyFactor: 1.3 },
        taxIncentives: {
            freeTradeZones: ['Iquique FTZ', 'Arica FTZ'],
            taxHolidayYears: 0,
            taxHolidayRate: 0.27,
            incentivePrograms: ['CORFO Technology Fund', 'Chile Green Hydrogen', 'Extreme Zone Tax Benefits'],
            importDutyExemption: false,
            landSubsidy: false,
            effectiveTaxRate: 0.27,
        },
        naturalDisaster: {
            seismicZone: 4,
            floodRisk: 'low',
            typhoonRisk: 'none',
            volcanoRisk: 'moderate',
            tsunamiRisk: 'high',
            compositeScore: 72,
            insuranceMultiplier: 1.7,
            structuralReinforcement: 0.15,
        },
        gridReliability: {
            gridUptime: 99.9,
            voltageStability: 'stable',
            brownoutFrequency: 3,
            averageOutageDuration: 15,
            gridTier: 1,
            backupFuelPremium: 0.03,
            recommendedGenHours: 48,
            renewableReadiness: 90,
        },
        talentPool: {
            dcEngineerPool: 'scarce',
            universityPipeline: 8,
            hyperscalerPresence: 3,
            avgHiringDays: 45,
            salaryPremium: 1.15,
            talentScore: 48,
            certifiedProfessionals: 180,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.20,
            dieselAvailability: 'moderate',
            hvoAvailable: false,
            hvoPricePerLiter: 0,
            fuelTaxRate: 0.06,
            deliveryLeadDays: 3,
            environmentalPermitRequired: true,
            storageLimitLiters: 50000,
            fuelQualityRating: 'high',
        },
        lastUpdated: '2025-Q1',
    },
    MX: {
        id: 'MX', region: 'LATAM', name: 'Mexico', currency: 'MXN', currencySymbol: 'MX$',
        economy: { inflationRate: 0.04, laborEscalation: 0.05, taxRate: 0.30, electricityRate: 0.09 },
        labor: {
            minimumWage: 350, baseSalary_ShiftLead: 1800, baseSalary_Engineer: 1400,
            baseSalary_Technician: 850, baseSalary_Admin: 600, baseSalary_Janitor: 350,
            laborRatePerHour: 10,
            overtimeRules: { workday: { firstHour: 2.0, subsequent: 3.0 }, holiday: { first8Hours: 2.0, ninthHour: 3.0, tenthHourPlus: 3.0 } },
            shrinkageFactor: 0.18, leaves: { annual: 12, publicHolidays: 7, sickAverage: 4 },
        },
        compliance: { certifications: ['NOM', 'SENER'], annualComplianceCost: 5000 },
        environment: { baselineAQI: 80, gridCarbonIntensity: 0.45 },
        risk: { downtimeCostPerMin: 1200 },
        supplyChain: { importDifficultyFactor: 1.15 },
        taxIncentives: {
            freeTradeZones: ['Queretaro SEZ', 'Bajio Industrial Corridor'],
            taxHolidayYears: 0,
            taxHolidayRate: 0.30,
            incentivePrograms: ['Nearshoring Tax Incentive', 'IMMEX Maquiladora', 'CONACYT R&D Support'],
            importDutyExemption: true,
            landSubsidy: false,
            effectiveTaxRate: 0.30,
        },
        naturalDisaster: {
            seismicZone: 3,
            floodRisk: 'moderate',
            typhoonRisk: 'moderate',
            volcanoRisk: 'moderate',
            tsunamiRisk: 'moderate',
            compositeScore: 62,
            insuranceMultiplier: 1.5,
            structuralReinforcement: 0.10,
        },
        gridReliability: {
            gridUptime: 99.7,
            voltageStability: 'moderate',
            brownoutFrequency: 12,
            averageOutageDuration: 35,
            gridTier: 2,
            backupFuelPremium: 0.10,
            recommendedGenHours: 72,
            renewableReadiness: 70,
        },
        talentPool: {
            dcEngineerPool: 'moderate',
            universityPipeline: 35,
            hyperscalerPresence: 4,
            avgHiringDays: 35,
            salaryPremium: 1.05,
            talentScore: 55,
            certifiedProfessionals: 300,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.05,
            dieselAvailability: 'abundant',
            hvoAvailable: false,
            hvoPricePerLiter: 0,
            fuelTaxRate: 0.08,
            deliveryLeadDays: 2,
            environmentalPermitRequired: true,
            storageLimitLiters: 60000,
            fuelQualityRating: 'moderate',
        },
        lastUpdated: '2025-Q1',
    },
    CO: {
        id: 'CO', region: 'LATAM', name: 'Colombia', currency: 'COP', currencySymbol: 'CO$',
        economy: { inflationRate: 0.06, laborEscalation: 0.055, taxRate: 0.35, electricityRate: 0.08 },
        labor: {
            minimumWage: 280, baseSalary_ShiftLead: 1600, baseSalary_Engineer: 1200,
            baseSalary_Technician: 700, baseSalary_Admin: 500, baseSalary_Janitor: 300,
            laborRatePerHour: 8,
            overtimeRules: { workday: { firstHour: 1.25, subsequent: 1.75 }, holiday: { first8Hours: 1.75, ninthHour: 2.0, tenthHourPlus: 2.0 } },
            shrinkageFactor: 0.20, leaves: { annual: 15, publicHolidays: 18, sickAverage: 4 },
        },
        compliance: { certifications: ['RETIE', 'SIC'], annualComplianceCost: 4000 },
        environment: { baselineAQI: 55, gridCarbonIntensity: 0.2 },
        risk: { downtimeCostPerMin: 1000 },
        supplyChain: { importDifficultyFactor: 1.35 },
        taxIncentives: {
            freeTradeZones: ['Zona Franca Bogota', 'Zona Franca del Pacifico'],
            taxHolidayYears: 5,
            taxHolidayRate: 0.20,
            incentivePrograms: ['Free Zone 20% Rate', 'Orange Economy Tax Benefits', 'Mega-Investment Incentive'],
            importDutyExemption: true,
            landSubsidy: false,
            effectiveTaxRate: 0.20,
        },
        naturalDisaster: {
            seismicZone: 3,
            floodRisk: 'high',
            typhoonRisk: 'none',
            volcanoRisk: 'moderate',
            tsunamiRisk: 'low',
            compositeScore: 52,
            insuranceMultiplier: 1.4,
            structuralReinforcement: 0.08,
        },
        gridReliability: {
            gridUptime: 99.5,
            voltageStability: 'moderate',
            brownoutFrequency: 15,
            averageOutageDuration: 40,
            gridTier: 2,
            backupFuelPremium: 0.12,
            recommendedGenHours: 72,
            renewableReadiness: 60,
        },
        talentPool: {
            dcEngineerPool: 'scarce',
            universityPipeline: 12,
            hyperscalerPresence: 2,
            avgHiringDays: 50,
            salaryPremium: 1.15,
            talentScore: 40,
            certifiedProfessionals: 120,
        },
        fuelDiesel: {
            dieselPricePerLiter: 0.85,
            dieselAvailability: 'moderate',
            hvoAvailable: false,
            hvoPricePerLiter: 0,
            fuelTaxRate: 0.05,
            deliveryLeadDays: 4,
            environmentalPermitRequired: true,
            storageLimitLiters: 40000,
            fuelQualityRating: 'moderate',
        },
        lastUpdated: '2025-Q1',
    },
    // ─── EXPANDED APAC ──────────────────────────────────────
    IN: {
        id: 'IN', region: 'APAC', name: 'India', currency: 'INR', currencySymbol: '₹',
        economy: { inflationRate: 0.05, laborEscalation: 0.07, taxRate: 0.2517, electricityRate: 0.07 },
        labor: {
            minimumWage: 200, baseSalary_ShiftLead: 1200, baseSalary_Engineer: 900,
            baseSalary_Technician: 500, baseSalary_Admin: 400, baseSalary_Janitor: 200,
            laborRatePerHour: 8,
            overtimeRules: { workday: { firstHour: 2.0, subsequent: 2.0 }, holiday: { first8Hours: 2.0, ninthHour: 2.0, tenthHourPlus: 2.0 } },
            shrinkageFactor: 0.20, leaves: { annual: 12, publicHolidays: 16, sickAverage: 6 },
        },
        compliance: { certifications: ['BIS', 'CEA Regulations', 'LEED India'], annualComplianceCost: 4000 },
        environment: { baselineAQI: 150, gridCarbonIntensity: 0.72 },
        risk: { downtimeCostPerMin: 1200 },
        supplyChain: { importDifficultyFactor: 1.2 },
        taxIncentives: {
            freeTradeZones: ['SEEPZ Mumbai', 'Mahindra World City', 'GIFT City Gujarat'],
            taxHolidayYears: 10,
            taxHolidayRate: 0.15,
            incentivePrograms: ['IT/ITES SEZ Tax Holiday', 'GIFT City IFSC Benefits', 'PLI Scheme for IT Hardware'],
            importDutyExemption: true,
            landSubsidy: true,
            effectiveTaxRate: 0.15,
        },
        naturalDisaster: {
            seismicZone: 3,
            floodRisk: 'extreme',
            typhoonRisk: 'moderate',
            volcanoRisk: 'none',
            tsunamiRisk: 'moderate',
            compositeScore: 58,
            insuranceMultiplier: 1.45,
            structuralReinforcement: 0.08,
        },
        gridReliability: {
            gridUptime: 99.0,
            voltageStability: 'moderate',
            brownoutFrequency: 30,
            averageOutageDuration: 60,
            gridTier: 2,
            backupFuelPremium: 0.20,
            recommendedGenHours: 96,
            renewableReadiness: 75,
        },
        talentPool: {
            dcEngineerPool: 'abundant',
            universityPipeline: 200,
            hyperscalerPresence: 6,
            avgHiringDays: 25,
            salaryPremium: 1.0,
            talentScore: 78,
            certifiedProfessionals: 2500,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.00,
            dieselAvailability: 'abundant',
            hvoAvailable: false,
            hvoPricePerLiter: 0,
            fuelTaxRate: 0.12,
            deliveryLeadDays: 3,
            environmentalPermitRequired: true,
            storageLimitLiters: 50000,
            fuelQualityRating: 'moderate',
        },
        lastUpdated: '2025-Q1',
    },
    CN: {
        id: 'CN', region: 'APAC', name: 'China', currency: 'CNY', currencySymbol: '¥',
        economy: { inflationRate: 0.02, laborEscalation: 0.06, taxRate: 0.25, electricityRate: 0.06 },
        labor: {
            minimumWage: 400, baseSalary_ShiftLead: 2000, baseSalary_Engineer: 1500,
            baseSalary_Technician: 900, baseSalary_Admin: 700, baseSalary_Janitor: 450,
            laborRatePerHour: 12,
            overtimeRules: { workday: { firstHour: 1.5, subsequent: 2.0 }, holiday: { first8Hours: 3.0, ninthHour: 3.0, tenthHourPlus: 3.0 } },
            shrinkageFactor: 0.15, leaves: { annual: 5, publicHolidays: 11, sickAverage: 3 },
        },
        compliance: { certifications: ['GB Standards', 'MIIT License', 'Green DC Rating'], annualComplianceCost: 8000 },
        environment: { baselineAQI: 130, gridCarbonIntensity: 0.58 },
        risk: { downtimeCostPerMin: 2500 },
        supplyChain: { importDifficultyFactor: 1.1 },
        taxIncentives: {
            freeTradeZones: ['Shanghai FTZ', 'Hainan FTP', 'Shenzhen Qianhai'],
            taxHolidayYears: 5,
            taxHolidayRate: 0.15,
            incentivePrograms: ['HNTE 15% Tax Rate', 'Western Development Strategy', 'New Infrastructure Initiative'],
            importDutyExemption: true,
            landSubsidy: true,
            effectiveTaxRate: 0.15,
        },
        naturalDisaster: {
            seismicZone: 2,
            floodRisk: 'high',
            typhoonRisk: 'moderate',
            volcanoRisk: 'none',
            tsunamiRisk: 'low',
            compositeScore: 42,
            insuranceMultiplier: 1.3,
            structuralReinforcement: 0.06,
        },
        gridReliability: {
            gridUptime: 99.95,
            voltageStability: 'stable',
            brownoutFrequency: 2,
            averageOutageDuration: 12,
            gridTier: 1,
            backupFuelPremium: 0.02,
            recommendedGenHours: 48,
            renewableReadiness: 60,
        },
        talentPool: {
            dcEngineerPool: 'abundant',
            universityPipeline: 300,
            hyperscalerPresence: 8,
            avgHiringDays: 20,
            salaryPremium: 1.0,
            talentScore: 85,
            certifiedProfessionals: 5000,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.10,
            dieselAvailability: 'abundant',
            hvoAvailable: false,
            hvoPricePerLiter: 0,
            fuelTaxRate: 0.05,
            deliveryLeadDays: 2,
            environmentalPermitRequired: true,
            storageLimitLiters: 80000,
            fuelQualityRating: 'moderate',
        },
        lastUpdated: '2025-Q1',
    },
    KR: {
        id: 'KR', region: 'APAC', name: 'South Korea', currency: 'KRW', currencySymbol: '₩',
        economy: { inflationRate: 0.025, laborEscalation: 0.035, taxRate: 0.22, electricityRate: 0.11 },
        labor: {
            minimumWage: 1500, baseSalary_ShiftLead: 4000, baseSalary_Engineer: 3200,
            baseSalary_Technician: 2400, baseSalary_Admin: 2000, baseSalary_Janitor: 1500,
            laborRatePerHour: 28,
            overtimeRules: { workday: { firstHour: 1.5, subsequent: 1.5 }, holiday: { first8Hours: 2.0, ninthHour: 2.0, tenthHourPlus: 2.0 } },
            shrinkageFactor: 0.10, leaves: { annual: 15, publicHolidays: 15, sickAverage: 3 },
        },
        compliance: { certifications: ['KS Standards', 'KISA DC Cert'], annualComplianceCost: 9000 },
        environment: { baselineAQI: 55, gridCarbonIntensity: 0.42 },
        risk: { downtimeCostPerMin: 3500 },
        supplyChain: { importDifficultyFactor: 1.0 },
        taxIncentives: {
            freeTradeZones: ['Incheon FEZ', 'Busan-Jinhae FEZ', 'Sejong Smart City'],
            taxHolidayYears: 5,
            taxHolidayRate: 0.0,
            incentivePrograms: ['FEZ Tax Exemption', 'Digital New Deal', 'K-Cloud Initiative'],
            importDutyExemption: true,
            landSubsidy: true,
            effectiveTaxRate: 0.0,
        },
        naturalDisaster: {
            seismicZone: 1,
            floodRisk: 'moderate',
            typhoonRisk: 'moderate',
            volcanoRisk: 'none',
            tsunamiRisk: 'low',
            compositeScore: 30,
            insuranceMultiplier: 1.15,
            structuralReinforcement: 0.03,
        },
        gridReliability: {
            gridUptime: 99.99,
            voltageStability: 'stable',
            brownoutFrequency: 0,
            averageOutageDuration: 3,
            gridTier: 1,
            backupFuelPremium: 0.0,
            recommendedGenHours: 24,
            renewableReadiness: 50,
        },
        talentPool: {
            dcEngineerPool: 'moderate',
            universityPipeline: 35,
            hyperscalerPresence: 5,
            avgHiringDays: 40,
            salaryPremium: 1.1,
            talentScore: 68,
            certifiedProfessionals: 900,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.30,
            dieselAvailability: 'abundant',
            hvoAvailable: true,
            hvoPricePerLiter: 2.50,
            fuelTaxRate: 0.10,
            deliveryLeadDays: 1,
            environmentalPermitRequired: true,
            storageLimitLiters: 60000,
            fuelQualityRating: 'high',
        },
        lastUpdated: '2025-Q1',
    },
    TH: {
        id: 'TH', region: 'APAC', name: 'Thailand', currency: 'THB', currencySymbol: '฿',
        economy: { inflationRate: 0.02, laborEscalation: 0.04, taxRate: 0.20, electricityRate: 0.08 },
        labor: {
            minimumWage: 300, baseSalary_ShiftLead: 1400, baseSalary_Engineer: 1000,
            baseSalary_Technician: 600, baseSalary_Admin: 450, baseSalary_Janitor: 300,
            laborRatePerHour: 8,
            overtimeRules: { workday: { firstHour: 1.5, subsequent: 2.0 }, holiday: { first8Hours: 2.0, ninthHour: 3.0, tenthHourPlus: 3.0 } },
            shrinkageFactor: 0.18, leaves: { annual: 6, publicHolidays: 16, sickAverage: 5 },
        },
        compliance: { certifications: ['TIS Standards', 'PEA License'], annualComplianceCost: 4500 },
        environment: { baselineAQI: 80, gridCarbonIntensity: 0.5 },
        risk: { downtimeCostPerMin: 1000 },
        supplyChain: { importDifficultyFactor: 1.15 },
        taxIncentives: {
            freeTradeZones: ['Eastern Seaboard (EEC)', 'Amata City', 'Hemaraj Industrial'],
            taxHolidayYears: 8,
            taxHolidayRate: 0.0,
            incentivePrograms: ['BOI DC Investment Promotion', 'EEC Digital Park', 'Thailand 4.0 Smart Electronics'],
            importDutyExemption: true,
            landSubsidy: true,
            effectiveTaxRate: 0.0,
        },
        naturalDisaster: {
            seismicZone: 1,
            floodRisk: 'extreme',
            typhoonRisk: 'low',
            volcanoRisk: 'none',
            tsunamiRisk: 'moderate',
            compositeScore: 40,
            insuranceMultiplier: 1.3,
            structuralReinforcement: 0.03,
        },
        gridReliability: {
            gridUptime: 99.8,
            voltageStability: 'moderate',
            brownoutFrequency: 8,
            averageOutageDuration: 25,
            gridTier: 2,
            backupFuelPremium: 0.08,
            recommendedGenHours: 48,
            renewableReadiness: 65,
        },
        talentPool: {
            dcEngineerPool: 'moderate',
            universityPipeline: 20,
            hyperscalerPresence: 4,
            avgHiringDays: 35,
            salaryPremium: 1.05,
            talentScore: 55,
            certifiedProfessionals: 280,
        },
        fuelDiesel: {
            dieselPricePerLiter: 0.85,
            dieselAvailability: 'abundant',
            hvoAvailable: false,
            hvoPricePerLiter: 0,
            fuelTaxRate: 0.05,
            deliveryLeadDays: 2,
            environmentalPermitRequired: true,
            storageLimitLiters: 50000,
            fuelQualityRating: 'moderate',
        },
        lastUpdated: '2025-Q1',
    },
    VN: {
        id: 'VN', region: 'APAC', name: 'Vietnam', currency: 'VND', currencySymbol: '₫',
        economy: { inflationRate: 0.035, laborEscalation: 0.07, taxRate: 0.20, electricityRate: 0.07 },
        labor: {
            minimumWage: 200, baseSalary_ShiftLead: 1100, baseSalary_Engineer: 800,
            baseSalary_Technician: 450, baseSalary_Admin: 350, baseSalary_Janitor: 200,
            laborRatePerHour: 6,
            overtimeRules: { workday: { firstHour: 1.5, subsequent: 2.0 }, holiday: { first8Hours: 3.0, ninthHour: 3.0, tenthHourPlus: 3.0 } },
            shrinkageFactor: 0.22, leaves: { annual: 12, publicHolidays: 10, sickAverage: 5 },
        },
        compliance: { certifications: ['TCVN', 'MOIT License'], annualComplianceCost: 3500 },
        environment: { baselineAQI: 100, gridCarbonIntensity: 0.55 },
        risk: { downtimeCostPerMin: 800 },
        supplyChain: { importDifficultyFactor: 1.3 },
        taxIncentives: {
            freeTradeZones: ['Saigon Hi-Tech Park', 'Da Nang IT Park', 'VSIP Binh Duong'],
            taxHolidayYears: 4,
            taxHolidayRate: 0.0,
            incentivePrograms: ['CIT Preferential Rate 10%', 'Hi-Tech Enterprise Incentive', 'Digital Infrastructure Investment'],
            importDutyExemption: true,
            landSubsidy: true,
            effectiveTaxRate: 0.0,
        },
        naturalDisaster: {
            seismicZone: 1,
            floodRisk: 'extreme',
            typhoonRisk: 'high',
            volcanoRisk: 'none',
            tsunamiRisk: 'low',
            compositeScore: 48,
            insuranceMultiplier: 1.35,
            structuralReinforcement: 0.05,
        },
        gridReliability: {
            gridUptime: 99.2,
            voltageStability: 'moderate',
            brownoutFrequency: 20,
            averageOutageDuration: 50,
            gridTier: 2,
            backupFuelPremium: 0.18,
            recommendedGenHours: 72,
            renewableReadiness: 55,
        },
        talentPool: {
            dcEngineerPool: 'moderate',
            universityPipeline: 30,
            hyperscalerPresence: 3,
            avgHiringDays: 35,
            salaryPremium: 1.05,
            talentScore: 50,
            certifiedProfessionals: 200,
        },
        fuelDiesel: {
            dieselPricePerLiter: 0.90,
            dieselAvailability: 'moderate',
            hvoAvailable: false,
            hvoPricePerLiter: 0,
            fuelTaxRate: 0.07,
            deliveryLeadDays: 3,
            environmentalPermitRequired: true,
            storageLimitLiters: 40000,
            fuelQualityRating: 'moderate',
        },
        lastUpdated: '2025-Q1',
    },
    PH: {
        id: 'PH', region: 'APAC', name: 'Philippines', currency: 'PHP', currencySymbol: '₱',
        economy: { inflationRate: 0.05, laborEscalation: 0.05, taxRate: 0.25, electricityRate: 0.10 },
        labor: {
            minimumWage: 250, baseSalary_ShiftLead: 1300, baseSalary_Engineer: 1000,
            baseSalary_Technician: 550, baseSalary_Admin: 400, baseSalary_Janitor: 250,
            laborRatePerHour: 7,
            overtimeRules: { workday: { firstHour: 1.25, subsequent: 1.3 }, holiday: { first8Hours: 2.0, ninthHour: 2.0, tenthHourPlus: 2.6 } },
            shrinkageFactor: 0.22, leaves: { annual: 5, publicHolidays: 18, sickAverage: 5 },
        },
        compliance: { certifications: ['PNS Standards', 'DOE License'], annualComplianceCost: 3500 },
        environment: { baselineAQI: 70, gridCarbonIntensity: 0.6 },
        risk: { downtimeCostPerMin: 900 },
        supplyChain: { importDifficultyFactor: 1.35 },
        taxIncentives: {
            freeTradeZones: ['PEZA Zones (400+)', 'Clark Freeport', 'Subic Bay Freeport'],
            taxHolidayYears: 7,
            taxHolidayRate: 0.0,
            incentivePrograms: ['CREATE MORE Act', 'PEZA IT Enterprise', 'Green Lane for DC Equipment'],
            importDutyExemption: true,
            landSubsidy: false,
            effectiveTaxRate: 0.0,
        },
        naturalDisaster: {
            seismicZone: 3,
            floodRisk: 'extreme',
            typhoonRisk: 'high',
            volcanoRisk: 'moderate',
            tsunamiRisk: 'moderate',
            compositeScore: 78,
            insuranceMultiplier: 1.75,
            structuralReinforcement: 0.14,
        },
        gridReliability: {
            gridUptime: 98.0,
            voltageStability: 'unstable',
            brownoutFrequency: 40,
            averageOutageDuration: 60,
            gridTier: 3,
            backupFuelPremium: 0.25,
            recommendedGenHours: 96,
            renewableReadiness: 60,
        },
        talentPool: {
            dcEngineerPool: 'moderate',
            universityPipeline: 22,
            hyperscalerPresence: 3,
            avgHiringDays: 30,
            salaryPremium: 1.05,
            talentScore: 55,
            certifiedProfessionals: 250,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.00,
            dieselAvailability: 'moderate',
            hvoAvailable: false,
            hvoPricePerLiter: 0,
            fuelTaxRate: 0.06,
            deliveryLeadDays: 3,
            environmentalPermitRequired: true,
            storageLimitLiters: 40000,
            fuelQualityRating: 'moderate',
        },
        lastUpdated: '2025-Q1',
    },
    TW: {
        id: 'TW', region: 'APAC', name: 'Taiwan', currency: 'TWD', currencySymbol: 'NT$',
        economy: { inflationRate: 0.02, laborEscalation: 0.03, taxRate: 0.20, electricityRate: 0.09 },
        labor: {
            minimumWage: 900, baseSalary_ShiftLead: 2800, baseSalary_Engineer: 2200,
            baseSalary_Technician: 1600, baseSalary_Admin: 1200, baseSalary_Janitor: 900,
            laborRatePerHour: 20,
            overtimeRules: { workday: { firstHour: 1.34, subsequent: 1.67 }, holiday: { first8Hours: 2.0, ninthHour: 2.0, tenthHourPlus: 2.0 } },
            shrinkageFactor: 0.12, leaves: { annual: 7, publicHolidays: 12, sickAverage: 4 },
        },
        compliance: { certifications: ['CNS Standards', 'Taipower License'], annualComplianceCost: 7000 },
        environment: { baselineAQI: 60, gridCarbonIntensity: 0.5 },
        risk: { downtimeCostPerMin: 3000 },
        supplyChain: { importDifficultyFactor: 1.05 },
        taxIncentives: {
            freeTradeZones: ['Hsinchu Science Park', 'Kaohsiung Software Park'],
            taxHolidayYears: 5,
            taxHolidayRate: 0.0,
            incentivePrograms: ['Smart Machinery Tax Credit', 'Industrial Innovation Act', 'Asia Silicon Valley Plan'],
            importDutyExemption: true,
            landSubsidy: false,
            effectiveTaxRate: 0.0,
        },
        naturalDisaster: {
            seismicZone: 4,
            floodRisk: 'moderate',
            typhoonRisk: 'high',
            volcanoRisk: 'low',
            tsunamiRisk: 'moderate',
            compositeScore: 75,
            insuranceMultiplier: 1.7,
            structuralReinforcement: 0.16,
        },
        gridReliability: {
            gridUptime: 99.9,
            voltageStability: 'stable',
            brownoutFrequency: 3,
            averageOutageDuration: 15,
            gridTier: 1,
            backupFuelPremium: 0.03,
            recommendedGenHours: 48,
            renewableReadiness: 50,
        },
        talentPool: {
            dcEngineerPool: 'moderate',
            universityPipeline: 18,
            hyperscalerPresence: 5,
            avgHiringDays: 40,
            salaryPremium: 1.1,
            talentScore: 65,
            certifiedProfessionals: 650,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.05,
            dieselAvailability: 'abundant',
            hvoAvailable: false,
            hvoPricePerLiter: 0,
            fuelTaxRate: 0.05,
            deliveryLeadDays: 2,
            environmentalPermitRequired: true,
            storageLimitLiters: 50000,
            fuelQualityRating: 'high',
        },
        lastUpdated: '2025-Q1',
    },
    NZ: {
        id: 'NZ', region: 'APAC', name: 'New Zealand', currency: 'NZD', currencySymbol: 'NZ$',
        economy: { inflationRate: 0.03, laborEscalation: 0.035, taxRate: 0.28, electricityRate: 0.16 },
        labor: {
            minimumWage: 2500, baseSalary_ShiftLead: 7500, baseSalary_Engineer: 6000,
            baseSalary_Technician: 4500, baseSalary_Admin: 3800, baseSalary_Janitor: 3000,
            laborRatePerHour: 38,
            overtimeRules: { workday: { firstHour: 1.5, subsequent: 1.5 }, holiday: { first8Hours: 2.0, ninthHour: 2.0, tenthHourPlus: 2.0 } },
            shrinkageFactor: 0.12, leaves: { annual: 20, publicHolidays: 11, sickAverage: 5 },
        },
        compliance: { certifications: ['AS/NZS Standards', 'WorkSafe'], annualComplianceCost: 8000 },
        environment: { baselineAQI: 15, gridCarbonIntensity: 0.1 },
        risk: { downtimeCostPerMin: 4000 },
        supplyChain: { importDifficultyFactor: 1.25 },
        taxIncentives: {
            freeTradeZones: [],
            taxHolidayYears: 0,
            taxHolidayRate: 0.28,
            incentivePrograms: ['Callaghan Innovation R&D Grant', 'NZ Green Investment Fund'],
            importDutyExemption: false,
            landSubsidy: false,
            effectiveTaxRate: 0.28,
        },
        naturalDisaster: {
            seismicZone: 4,
            floodRisk: 'moderate',
            typhoonRisk: 'none',
            volcanoRisk: 'moderate',
            tsunamiRisk: 'moderate',
            compositeScore: 65,
            insuranceMultiplier: 1.6,
            structuralReinforcement: 0.14,
        },
        gridReliability: {
            gridUptime: 99.98,
            voltageStability: 'stable',
            brownoutFrequency: 1,
            averageOutageDuration: 5,
            gridTier: 1,
            backupFuelPremium: 0.0,
            recommendedGenHours: 48,
            renewableReadiness: 90,
        },
        talentPool: {
            dcEngineerPool: 'scarce',
            universityPipeline: 3,
            hyperscalerPresence: 2,
            avgHiringDays: 50,
            salaryPremium: 1.2,
            talentScore: 42,
            certifiedProfessionals: 150,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.40,
            dieselAvailability: 'moderate',
            hvoAvailable: true,
            hvoPricePerLiter: 2.60,
            fuelTaxRate: 0.08,
            deliveryLeadDays: 3,
            environmentalPermitRequired: true,
            storageLimitLiters: 40000,
            fuelQualityRating: 'high',
        },
        lastUpdated: '2025-Q1',
    },
    // ─── EXPANDED EMEA ──────────────────────────────────────
    GB: {
        id: 'GB', region: 'EMEA', name: 'United Kingdom', currency: 'GBP', currencySymbol: '£',
        economy: { inflationRate: 0.03, laborEscalation: 0.035, taxRate: 0.25, electricityRate: 0.20 },
        labor: {
            minimumWage: 2200, baseSalary_ShiftLead: 8000, baseSalary_Engineer: 6500,
            baseSalary_Technician: 4500, baseSalary_Admin: 3500, baseSalary_Janitor: 2500,
            laborRatePerHour: 38,
            overtimeRules: { workday: { firstHour: 1.5, subsequent: 1.5 }, holiday: { first8Hours: 2.0, ninthHour: 2.0, tenthHourPlus: 2.0 } },
            shrinkageFactor: 0.12, leaves: { annual: 28, publicHolidays: 8, sickAverage: 5 },
        },
        compliance: { certifications: ['BS EN Standards', 'IET Wiring Regs', 'BREEAM'], annualComplianceCost: 14000 },
        environment: { baselineAQI: 25, gridCarbonIntensity: 0.23 },
        risk: { downtimeCostPerMin: 4500 },
        supplyChain: { importDifficultyFactor: 1.0 },
        taxIncentives: {
            freeTradeZones: ['London Docklands Enterprise Zone'],
            taxHolidayYears: 0,
            taxHolidayRate: 0.25,
            incentivePrograms: ['R&D Tax Credit (RDEC)', 'Capital Allowances Super Deduction', 'Enterprise Zones'],
            importDutyExemption: false,
            landSubsidy: false,
            effectiveTaxRate: 0.25,
        },
        naturalDisaster: {
            seismicZone: 0,
            floodRisk: 'moderate',
            typhoonRisk: 'none',
            volcanoRisk: 'none',
            tsunamiRisk: 'none',
            compositeScore: 10,
            insuranceMultiplier: 1.05,
            structuralReinforcement: 0.0,
        },
        gridReliability: {
            gridUptime: 99.99,
            voltageStability: 'stable',
            brownoutFrequency: 0,
            averageOutageDuration: 3,
            gridTier: 1,
            backupFuelPremium: 0.0,
            recommendedGenHours: 24,
            renewableReadiness: 65,
        },
        talentPool: {
            dcEngineerPool: 'abundant',
            universityPipeline: 30,
            hyperscalerPresence: 7,
            avgHiringDays: 30,
            salaryPremium: 1.0,
            talentScore: 82,
            certifiedProfessionals: 3500,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.70,
            dieselAvailability: 'abundant',
            hvoAvailable: true,
            hvoPricePerLiter: 2.80,
            fuelTaxRate: 0.15,
            deliveryLeadDays: 1,
            environmentalPermitRequired: true,
            storageLimitLiters: 60000,
            fuelQualityRating: 'high',
        },
        lastUpdated: '2025-Q1',
    },
    DE: {
        id: 'DE', region: 'EMEA', name: 'Germany', currency: 'EUR', currencySymbol: '€',
        economy: { inflationRate: 0.025, laborEscalation: 0.03, taxRate: 0.2975, electricityRate: 0.30 },
        labor: {
            minimumWage: 2400, baseSalary_ShiftLead: 8500, baseSalary_Engineer: 7000,
            baseSalary_Technician: 5000, baseSalary_Admin: 4000, baseSalary_Janitor: 2800,
            laborRatePerHour: 42,
            overtimeRules: { workday: { firstHour: 1.25, subsequent: 1.5 }, holiday: { first8Hours: 2.0, ninthHour: 2.0, tenthHourPlus: 2.0 } },
            shrinkageFactor: 0.12, leaves: { annual: 24, publicHolidays: 10, sickAverage: 8 },
        },
        compliance: { certifications: ['VDE', 'TÜV', 'EnEfG'], annualComplianceCost: 16000 },
        environment: { baselineAQI: 20, gridCarbonIntensity: 0.35 },
        risk: { downtimeCostPerMin: 5000 },
        supplyChain: { importDifficultyFactor: 1.0 },
        taxIncentives: {
            freeTradeZones: [],
            taxHolidayYears: 0,
            taxHolidayRate: 0.2975,
            incentivePrograms: ['R&D Tax Allowance (Forschungszulage)', 'EnEfG Compliance Credits', 'Investment Grants (GRW)'],
            importDutyExemption: false,
            landSubsidy: false,
            effectiveTaxRate: 0.2975,
        },
        naturalDisaster: {
            seismicZone: 1,
            floodRisk: 'moderate',
            typhoonRisk: 'none',
            volcanoRisk: 'none',
            tsunamiRisk: 'none',
            compositeScore: 12,
            insuranceMultiplier: 1.05,
            structuralReinforcement: 0.01,
        },
        gridReliability: {
            gridUptime: 99.998,
            voltageStability: 'stable',
            brownoutFrequency: 0,
            averageOutageDuration: 2,
            gridTier: 1,
            backupFuelPremium: 0.0,
            recommendedGenHours: 24,
            renewableReadiness: 70,
        },
        talentPool: {
            dcEngineerPool: 'abundant',
            universityPipeline: 40,
            hyperscalerPresence: 6,
            avgHiringDays: 35,
            salaryPremium: 1.0,
            talentScore: 80,
            certifiedProfessionals: 2800,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.80,
            dieselAvailability: 'abundant',
            hvoAvailable: true,
            hvoPricePerLiter: 3.00,
            fuelTaxRate: 0.15,
            deliveryLeadDays: 1,
            environmentalPermitRequired: true,
            storageLimitLiters: 60000,
            fuelQualityRating: 'high',
        },
        lastUpdated: '2025-Q1',
    },
    NL: {
        id: 'NL', region: 'EMEA', name: 'Netherlands', currency: 'EUR', currencySymbol: '€',
        economy: { inflationRate: 0.025, laborEscalation: 0.03, taxRate: 0.2575, electricityRate: 0.22 },
        labor: {
            minimumWage: 2200, baseSalary_ShiftLead: 7500, baseSalary_Engineer: 6000,
            baseSalary_Technician: 4500, baseSalary_Admin: 3500, baseSalary_Janitor: 2500,
            laborRatePerHour: 38,
            overtimeRules: { workday: { firstHour: 1.3, subsequent: 1.5 }, holiday: { first8Hours: 2.0, ninthHour: 2.0, tenthHourPlus: 2.0 } },
            shrinkageFactor: 0.10, leaves: { annual: 25, publicHolidays: 8, sickAverage: 5 },
        },
        compliance: { certifications: ['NEN Standards', 'BREEAM-NL'], annualComplianceCost: 13000 },
        environment: { baselineAQI: 20, gridCarbonIntensity: 0.33 },
        risk: { downtimeCostPerMin: 4500 },
        supplyChain: { importDifficultyFactor: 1.0 },
        taxIncentives: {
            freeTradeZones: ['Amsterdam Schiphol Logistics Park'],
            taxHolidayYears: 0,
            taxHolidayRate: 0.2575,
            incentivePrograms: ['Innovation Box (9% rate)', 'WBSO R&D Tax Credit', 'EIA Energy Investment Allowance'],
            importDutyExemption: false,
            landSubsidy: false,
            effectiveTaxRate: 0.2575,
        },
        naturalDisaster: {
            seismicZone: 0,
            floodRisk: 'moderate',
            typhoonRisk: 'none',
            volcanoRisk: 'none',
            tsunamiRisk: 'none',
            compositeScore: 15,
            insuranceMultiplier: 1.1,
            structuralReinforcement: 0.0,
        },
        gridReliability: {
            gridUptime: 99.998,
            voltageStability: 'stable',
            brownoutFrequency: 0,
            averageOutageDuration: 2,
            gridTier: 1,
            backupFuelPremium: 0.0,
            recommendedGenHours: 24,
            renewableReadiness: 60,
        },
        talentPool: {
            dcEngineerPool: 'abundant',
            universityPipeline: 12,
            hyperscalerPresence: 8,
            avgHiringDays: 30,
            salaryPremium: 1.05,
            talentScore: 85,
            certifiedProfessionals: 2200,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.75,
            dieselAvailability: 'abundant',
            hvoAvailable: true,
            hvoPricePerLiter: 2.90,
            fuelTaxRate: 0.15,
            deliveryLeadDays: 1,
            environmentalPermitRequired: true,
            storageLimitLiters: 50000,
            fuelQualityRating: 'high',
        },
        lastUpdated: '2025-Q1',
    },
    IE: {
        id: 'IE', region: 'EMEA', name: 'Ireland', currency: 'EUR', currencySymbol: '€',
        economy: { inflationRate: 0.025, laborEscalation: 0.035, taxRate: 0.125, electricityRate: 0.20 },
        labor: {
            minimumWage: 2400, baseSalary_ShiftLead: 7800, baseSalary_Engineer: 6500,
            baseSalary_Technician: 4800, baseSalary_Admin: 3800, baseSalary_Janitor: 2800,
            laborRatePerHour: 36,
            overtimeRules: { workday: { firstHour: 1.5, subsequent: 1.5 }, holiday: { first8Hours: 2.0, ninthHour: 2.0, tenthHourPlus: 2.0 } },
            shrinkageFactor: 0.12, leaves: { annual: 20, publicHolidays: 9, sickAverage: 5 },
        },
        compliance: { certifications: ['IS EN Standards', 'SEAI BER'], annualComplianceCost: 14000 },
        environment: { baselineAQI: 15, gridCarbonIntensity: 0.3 },
        risk: { downtimeCostPerMin: 4500 },
        supplyChain: { importDifficultyFactor: 1.05 },
        taxIncentives: {
            freeTradeZones: ['Shannon Free Zone', 'IDA Technology Parks'],
            taxHolidayYears: 0,
            taxHolidayRate: 0.125,
            incentivePrograms: ['12.5% Corporate Rate', 'IDA Ireland Grants', 'R&D Tax Credit 25%', 'Knowledge Development Box 6.25%'],
            importDutyExemption: false,
            landSubsidy: true,
            effectiveTaxRate: 0.125,
        },
        naturalDisaster: {
            seismicZone: 0,
            floodRisk: 'moderate',
            typhoonRisk: 'none',
            volcanoRisk: 'none',
            tsunamiRisk: 'none',
            compositeScore: 8,
            insuranceMultiplier: 1.0,
            structuralReinforcement: 0.0,
        },
        gridReliability: {
            gridUptime: 99.97,
            voltageStability: 'stable',
            brownoutFrequency: 1,
            averageOutageDuration: 5,
            gridTier: 1,
            backupFuelPremium: 0.0,
            recommendedGenHours: 24,
            renewableReadiness: 65,
        },
        talentPool: {
            dcEngineerPool: 'moderate',
            universityPipeline: 8,
            hyperscalerPresence: 8,
            avgHiringDays: 40,
            salaryPremium: 1.15,
            talentScore: 70,
            certifiedProfessionals: 1200,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.65,
            dieselAvailability: 'abundant',
            hvoAvailable: true,
            hvoPricePerLiter: 2.70,
            fuelTaxRate: 0.12,
            deliveryLeadDays: 2,
            environmentalPermitRequired: true,
            storageLimitLiters: 50000,
            fuelQualityRating: 'high',
        },
        lastUpdated: '2025-Q1',
    },
    FR: {
        id: 'FR', region: 'EMEA', name: 'France', currency: 'EUR', currencySymbol: '€',
        economy: { inflationRate: 0.025, laborEscalation: 0.03, taxRate: 0.25, electricityRate: 0.13 },
        labor: {
            minimumWage: 2100, baseSalary_ShiftLead: 7000, baseSalary_Engineer: 5500,
            baseSalary_Technician: 4000, baseSalary_Admin: 3200, baseSalary_Janitor: 2300,
            laborRatePerHour: 35,
            overtimeRules: { workday: { firstHour: 1.25, subsequent: 1.5 }, holiday: { first8Hours: 2.0, ninthHour: 2.0, tenthHourPlus: 2.0 } },
            shrinkageFactor: 0.15, leaves: { annual: 25, publicHolidays: 11, sickAverage: 6 },
        },
        compliance: { certifications: ['NF C 15-100', 'AFNOR'], annualComplianceCost: 15000 },
        environment: { baselineAQI: 25, gridCarbonIntensity: 0.06 },
        risk: { downtimeCostPerMin: 4000 },
        supplyChain: { importDifficultyFactor: 1.0 },
        taxIncentives: {
            freeTradeZones: [],
            taxHolidayYears: 0,
            taxHolidayRate: 0.25,
            incentivePrograms: ['CIR R&D Tax Credit 30%', 'France 2030 Digital Infrastructure', 'Reduced Energy Tax for DCs'],
            importDutyExemption: false,
            landSubsidy: false,
            effectiveTaxRate: 0.25,
        },
        naturalDisaster: {
            seismicZone: 1,
            floodRisk: 'moderate',
            typhoonRisk: 'none',
            volcanoRisk: 'none',
            tsunamiRisk: 'none',
            compositeScore: 12,
            insuranceMultiplier: 1.05,
            structuralReinforcement: 0.01,
        },
        gridReliability: {
            gridUptime: 99.99,
            voltageStability: 'stable',
            brownoutFrequency: 0,
            averageOutageDuration: 3,
            gridTier: 1,
            backupFuelPremium: 0.0,
            recommendedGenHours: 24,
            renewableReadiness: 55,
        },
        talentPool: {
            dcEngineerPool: 'moderate',
            universityPipeline: 25,
            hyperscalerPresence: 5,
            avgHiringDays: 40,
            salaryPremium: 1.05,
            talentScore: 68,
            certifiedProfessionals: 1800,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.75,
            dieselAvailability: 'abundant',
            hvoAvailable: true,
            hvoPricePerLiter: 2.90,
            fuelTaxRate: 0.15,
            deliveryLeadDays: 1,
            environmentalPermitRequired: true,
            storageLimitLiters: 60000,
            fuelQualityRating: 'high',
        },
        lastUpdated: '2025-Q1',
    },
    SE: {
        id: 'SE', region: 'EMEA', name: 'Sweden', currency: 'SEK', currencySymbol: 'kr',
        economy: { inflationRate: 0.02, laborEscalation: 0.025, taxRate: 0.206, electricityRate: 0.08 },
        labor: {
            minimumWage: 2500, baseSalary_ShiftLead: 7200, baseSalary_Engineer: 6000,
            baseSalary_Technician: 4500, baseSalary_Admin: 3500, baseSalary_Janitor: 2800,
            laborRatePerHour: 36,
            overtimeRules: { workday: { firstHour: 1.5, subsequent: 2.0 }, holiday: { first8Hours: 2.0, ninthHour: 2.0, tenthHourPlus: 2.0 } },
            shrinkageFactor: 0.10, leaves: { annual: 25, publicHolidays: 13, sickAverage: 5 },
        },
        compliance: { certifications: ['SS Standards', 'Energimyndigheten'], annualComplianceCost: 12000 },
        environment: { baselineAQI: 10, gridCarbonIntensity: 0.04 },
        risk: { downtimeCostPerMin: 4000 },
        supplyChain: { importDifficultyFactor: 1.0 },
        taxIncentives: {
            freeTradeZones: ['Lulea Data Center Hub'],
            taxHolidayYears: 0,
            taxHolidayRate: 0.206,
            incentivePrograms: ['Reduced Energy Tax for DCs', 'Vinnova Innovation Grants', 'Northern Sweden Regional Aid'],
            importDutyExemption: false,
            landSubsidy: true,
            effectiveTaxRate: 0.206,
        },
        naturalDisaster: {
            seismicZone: 0,
            floodRisk: 'low',
            typhoonRisk: 'none',
            volcanoRisk: 'none',
            tsunamiRisk: 'none',
            compositeScore: 5,
            insuranceMultiplier: 1.0,
            structuralReinforcement: 0.0,
        },
        gridReliability: {
            gridUptime: 99.999,
            voltageStability: 'stable',
            brownoutFrequency: 0,
            averageOutageDuration: 1,
            gridTier: 1,
            backupFuelPremium: 0.0,
            recommendedGenHours: 24,
            renewableReadiness: 95,
        },
        talentPool: {
            dcEngineerPool: 'moderate',
            universityPipeline: 10,
            hyperscalerPresence: 3,
            avgHiringDays: 45,
            salaryPremium: 1.1,
            talentScore: 62,
            certifiedProfessionals: 600,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.85,
            dieselAvailability: 'abundant',
            hvoAvailable: true,
            hvoPricePerLiter: 2.80,
            fuelTaxRate: 0.18,
            deliveryLeadDays: 1,
            environmentalPermitRequired: true,
            storageLimitLiters: 50000,
            fuelQualityRating: 'high',
        },
        lastUpdated: '2025-Q1',
    },
    PL: {
        id: 'PL', region: 'EMEA', name: 'Poland', currency: 'PLN', currencySymbol: 'zł',
        economy: { inflationRate: 0.04, laborEscalation: 0.05, taxRate: 0.19, electricityRate: 0.12 },
        labor: {
            minimumWage: 1000, baseSalary_ShiftLead: 3500, baseSalary_Engineer: 2800,
            baseSalary_Technician: 2000, baseSalary_Admin: 1500, baseSalary_Janitor: 1000,
            laborRatePerHour: 15,
            overtimeRules: { workday: { firstHour: 1.5, subsequent: 2.0 }, holiday: { first8Hours: 2.0, ninthHour: 2.0, tenthHourPlus: 2.0 } },
            shrinkageFactor: 0.15, leaves: { annual: 20, publicHolidays: 13, sickAverage: 6 },
        },
        compliance: { certifications: ['PN-EN Standards', 'URE License'], annualComplianceCost: 7000 },
        environment: { baselineAQI: 40, gridCarbonIntensity: 0.65 },
        risk: { downtimeCostPerMin: 2000 },
        supplyChain: { importDifficultyFactor: 1.05 },
        taxIncentives: {
            freeTradeZones: ['Polish SEZ (14 zones)', 'Lodz SEZ', 'Katowice SEZ'],
            taxHolidayYears: 15,
            taxHolidayRate: 0.0,
            incentivePrograms: ['SEZ Tax Exemption', 'Polish Investment Zone', 'EU Structural Funds Co-financing'],
            importDutyExemption: false,
            landSubsidy: true,
            effectiveTaxRate: 0.0,
        },
        naturalDisaster: {
            seismicZone: 0,
            floodRisk: 'moderate',
            typhoonRisk: 'none',
            volcanoRisk: 'none',
            tsunamiRisk: 'none',
            compositeScore: 10,
            insuranceMultiplier: 1.05,
            structuralReinforcement: 0.0,
        },
        gridReliability: {
            gridUptime: 99.95,
            voltageStability: 'stable',
            brownoutFrequency: 2,
            averageOutageDuration: 10,
            gridTier: 1,
            backupFuelPremium: 0.02,
            recommendedGenHours: 48,
            renewableReadiness: 55,
        },
        talentPool: {
            dcEngineerPool: 'moderate',
            universityPipeline: 20,
            hyperscalerPresence: 4,
            avgHiringDays: 35,
            salaryPremium: 1.05,
            talentScore: 65,
            certifiedProfessionals: 800,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.45,
            dieselAvailability: 'abundant',
            hvoAvailable: false,
            hvoPricePerLiter: 0,
            fuelTaxRate: 0.10,
            deliveryLeadDays: 2,
            environmentalPermitRequired: true,
            storageLimitLiters: 50000,
            fuelQualityRating: 'high',
        },
        lastUpdated: '2025-Q1',
    },

    PT: {
        id: 'PT', region: 'EMEA', name: 'Portugal', currency: 'EUR', currencySymbol: '€',
        economy: { inflationRate: 0.023, laborEscalation: 0.035, taxRate: 0.20, electricityRate: 0.15 },
        labor: {
            minimumWage: 920, baseSalary_ShiftLead: 3800, baseSalary_Engineer: 2900,
            baseSalary_Technician: 2200, baseSalary_Admin: 1600, baseSalary_Janitor: 1050,
            laborRatePerHour: 18,
            overtimeRules: { workday: { firstHour: 1.25, subsequent: 1.5 }, holiday: { first8Hours: 2.0, ninthHour: 2.0, tenthHourPlus: 2.0 } },
            shrinkageFactor: 0.16, leaves: { annual: 22, publicHolidays: 13, sickAverage: 5 },
        },
        compliance: { certifications: ['ITED', 'ITUR', 'RGSPIE', 'DL 95/91'], annualComplianceCost: 14000 },
        environment: { baselineAQI: 20, gridCarbonIntensity: 0.08 },
        risk: { downtimeCostPerMin: 3500 },
        supplyChain: { importDifficultyFactor: 1.05 },
        taxIncentives: {
            freeTradeZones: ['Madeira Free Trade Zone', 'Sines Industrial Zone'],
            taxHolidayYears: 10,
            taxHolidayRate: 0.05,
            incentivePrograms: ['Portugal 2030 Program', 'SIFIDE R&D Tax Credit', 'Golden Visa Investment'],
            importDutyExemption: false,
            landSubsidy: false,
            effectiveTaxRate: 0.05,
        },
        naturalDisaster: {
            seismicZone: 2,
            floodRisk: 'low',
            typhoonRisk: 'none',
            volcanoRisk: 'none',
            tsunamiRisk: 'low',
            compositeScore: 25,
            insuranceMultiplier: 1.15,
            structuralReinforcement: 0.03,
        },
        gridReliability: {
            gridUptime: 99.97,
            voltageStability: 'stable',
            brownoutFrequency: 1,
            averageOutageDuration: 8,
            gridTier: 1,
            backupFuelPremium: 0.02,
            recommendedGenHours: 48,
            renewableReadiness: 68,
        },
        talentPool: {
            dcEngineerPool: 'moderate',
            universityPipeline: 15,
            hyperscalerPresence: 3,
            avgHiringDays: 40,
            salaryPremium: 1.0,
            talentScore: 55,
            certifiedProfessionals: 500,
        },
        fuelDiesel: {
            dieselPricePerLiter: 1.59,
            dieselAvailability: 'abundant',
            hvoAvailable: true,
            hvoPricePerLiter: 2.10,
            fuelTaxRate: 0.12,
            deliveryLeadDays: 2,
            environmentalPermitRequired: true,
            storageLimitLiters: 50000,
            fuelQualityRating: 'high',
        },
        lastUpdated: '2026-Q1',
    },
};
