/* AUTO-GENERATED by tools/build-engineering-symbols.mjs — DO NOT EDIT.
 * Source: assets/engineering/*.svg + manifest.json.
 * Per equipment kind: the inner SVG markup (IEC single-line-diagram symbols),
 * strokes = currentColor so the diagram recolours by lane. Authored in a
 * 0..48 coordinate box; SymbolGlyph translate/scales it to any size. */

export const SYMBOL_VIEWBOX = 48;

export type GenSymbolKind =
      'utility'
    | 'transformer'
    | 'switchgear'
    | 'genset'
    | 'fuel'
    | 'ups'
    | 'battery'
    | 'pdu'
    | 'rack'
    | 'fabric'
    | 'chiller'
    | 'coolingTower'
    | 'cdu'
    | 'crah'
    | 'bms'
    | 'itload'
    | 'breaker'
    | 'disconnect'
    | 'ats'
    | 'dryCooler'
    | 'solarArray'
    | 'inverter'
    | 'pump'
    | 'heatExchanger';

export interface GenSymbolMeta { label: string; category: string }

export const SYMBOL_META: Record<GenSymbolKind, GenSymbolMeta> = {
    utility: { label: "Utility Intake", category: "utility" },
    transformer: { label: "Transformer", category: "power" },
    switchgear: { label: "MV Switchgear", category: "power" },
    genset: { label: "Generator", category: "generation" },
    fuel: { label: "Fuel Farm", category: "generation" },
    ups: { label: "UPS System", category: "power" },
    battery: { label: "Battery", category: "power" },
    pdu: { label: "PDU", category: "distribution" },
    rack: { label: "Rack", category: "it" },
    fabric: { label: "Network Fabric", category: "it" },
    chiller: { label: "Chiller", category: "cooling" },
    coolingTower: { label: "Cooling Tower", category: "cooling" },
    cdu: { label: "CDU", category: "cooling" },
    crah: { label: "CRAH / AHU", category: "cooling" },
    bms: { label: "BMS / DCIM", category: "control" },
    itload: { label: "IT Load", category: "it" },
    breaker: { label: "Circuit Breaker", category: "power" },
    disconnect: { label: "Disconnect Switch", category: "power" },
    ats: { label: "Transfer Switch", category: "power" },
    dryCooler: { label: "Dry Cooler", category: "cooling" },
    solarArray: { label: "Solar PV Array", category: "renewable" },
    inverter: { label: "PCS / Inverter", category: "renewable" },
    pump: { label: "Pump", category: "cooling" },
    heatExchanger: { label: "Heat Exchanger", category: "cooling" },
};

/** Inner SVG markup per kind (paths/shapes only; currentColor strokes). */
export const SYMBOL_MARKUP: Record<GenSymbolKind, string> = {
    utility: "<path d=\"M24 4 L11 44 M24 4 L37 44\" /><path d=\"M16 26 L32 38 M32 26 L16 38\" stroke-width=\"1.3\" /><path d=\"M7 16 H41 M10 30 H38\" /><path d=\"M9 16 v4 M39 16 v4 M14 30 v4 M34 30 v4\" stroke-width=\"1.4\" /><path d=\"M24 8 v4\" stroke-width=\"1.4\" />",
    transformer: "<circle cx=\"24\" cy=\"18\" r=\"11\" /><circle cx=\"24\" cy=\"30\" r=\"11\" /><path d=\"M24 2 v5 M24 41 v5\" stroke-width=\"1.6\" />",
    switchgear: "<rect x=\"8\" y=\"7\" width=\"32\" height=\"34\" rx=\"2\" /><path d=\"M24 11 V19 M24 20 L34 29 M24 30 V38\" stroke-width=\"1.8\" /><circle cx=\"24\" cy=\"19.5\" r=\"1.7\" fill=\"currentColor\" stroke=\"none\" /><circle cx=\"24\" cy=\"29.5\" r=\"1.7\" fill=\"currentColor\" stroke=\"none\" /><path d=\"M14 7 v-3 M34 7 v-3\" stroke-width=\"1.4\" />",
    genset: "<rect x=\"4\" y=\"16\" width=\"17\" height=\"20\" rx=\"2\" /><path d=\"M8 16 v-4 h4 M15 16 v-4 h4\" stroke-width=\"1.3\" /><path d=\"M21 26 H26\" stroke-width=\"1.8\" /><circle cx=\"34\" cy=\"26\" r=\"10\" /><text x=\"34\" y=\"30.5\" font-family=\"sans-serif\" font-size=\"13\" font-weight=\"700\" text-anchor=\"middle\" fill=\"currentColor\" stroke=\"none\">G</text>",
    fuel: "<rect x=\"5\" y=\"15\" width=\"38\" height=\"20\" rx=\"10\" /><path d=\"M9 25 H39\" stroke-width=\"1.2\" stroke-dasharray=\"3 2.5\" /><path d=\"M24 15 V8 h5\" stroke-width=\"1.5\" /><path d=\"M13 35 v6 M35 35 v6\" stroke-width=\"1.6\" />",
    ups: "<rect x=\"4\" y=\"10\" width=\"26\" height=\"28\" rx=\"2\" /><path d=\"M6 36 L28 12\" stroke-width=\"1.2\" /><path d=\"M9 18 q3 -4 6 0 q3 4 6 0\" stroke-width=\"1.4\" /><path d=\"M10 28 H22 M10 32 H18\" stroke-width=\"1.4\" /><rect x=\"34\" y=\"14\" width=\"10\" height=\"20\" rx=\"1.5\" /><path d=\"M34 22 H44 M34 27 H44\" stroke-width=\"1.2\" /><path d=\"M37 14 v-3 h4\" stroke-width=\"1.3\" /><path d=\"M30 24 H34\" stroke-width=\"1.4\" />",
    battery: "<path d=\"M12 12 V36\" /><path d=\"M20 18 V30\" /><path d=\"M28 12 V36\" /><path d=\"M36 18 V30\" /><path d=\"M6 24 H12 M36 24 H42\" stroke-width=\"1.5\" />",
    pdu: "<rect x=\"10\" y=\"6\" width=\"28\" height=\"36\" rx=\"2\" /><path d=\"M14 15 H34 M14 22 H34\" stroke-width=\"1.3\" /><circle cx=\"17\" cy=\"30\" r=\"2\" fill=\"currentColor\" stroke=\"none\" /><circle cx=\"24\" cy=\"30\" r=\"2\" fill=\"currentColor\" stroke=\"none\" /><circle cx=\"31\" cy=\"30\" r=\"2\" fill=\"currentColor\" stroke=\"none\" /><circle cx=\"17\" cy=\"37\" r=\"2\" fill=\"currentColor\" stroke=\"none\" /><circle cx=\"24\" cy=\"37\" r=\"2\" fill=\"currentColor\" stroke=\"none\" /><circle cx=\"31\" cy=\"37\" r=\"2\" fill=\"currentColor\" stroke=\"none\" />",
    rack: "<rect x=\"10\" y=\"4\" width=\"28\" height=\"40\" rx=\"2\" /><path d=\"M15 4 V44 M33 4 V44\" stroke-width=\"1.1\" /><path d=\"M15 11 H33 M15 17 H33 M15 23 H33 M15 29 H33 M15 35 H33\" stroke-width=\"1.2\" /><circle cx=\"30\" cy=\"14\" r=\"1.2\" fill=\"currentColor\" stroke=\"none\" /><circle cx=\"30\" cy=\"26\" r=\"1.2\" fill=\"currentColor\" stroke=\"none\" />",
    fabric: "<path d=\"M15 14 L10 34 M15 14 L24 34 M15 14 L38 34 M33 14 L10 34 M33 14 L24 34 M33 14 L38 34\" stroke-width=\"1.1\" /><circle cx=\"15\" cy=\"13\" r=\"4.5\" /><circle cx=\"33\" cy=\"13\" r=\"4.5\" /><circle cx=\"10\" cy=\"35\" r=\"4.5\" /><circle cx=\"24\" cy=\"35\" r=\"4.5\" /><circle cx=\"38\" cy=\"35\" r=\"4.5\" />",
    chiller: "<circle cx=\"24\" cy=\"12\" r=\"7\" /><path d=\"M21 12 L27 8 V16 Z\" stroke-width=\"1.3\" /><rect x=\"7\" y=\"22\" width=\"34\" height=\"8\" rx=\"4\" /><rect x=\"7\" y=\"34\" width=\"34\" height=\"8\" rx=\"4\" /><path d=\"M15 19 V22 M33 19 V22 M15 30 V34 M33 30 V34\" stroke-width=\"1.3\" />",
    coolingTower: "<path d=\"M11 43 C17 27 17 21 13 6 H35 C31 21 31 27 37 43 Z\" /><circle cx=\"24\" cy=\"12\" r=\"5\" stroke-width=\"1.4\" /><path d=\"M19 12 H29 M24 7 V17\" stroke-width=\"1.4\" /><path d=\"M15 30 H33 M14 36 H34\" stroke-width=\"1.2\" />",
    cdu: "<circle cx=\"14\" cy=\"24\" r=\"9\" /><path d=\"M14 15 L21 24 L14 33\" stroke-width=\"1.4\" /><rect x=\"28\" y=\"12\" width=\"16\" height=\"24\" rx=\"1.5\" /><path d=\"M32 12 V36 M36 12 V36 M40 12 V36\" stroke-width=\"1.2\" />",
    crah: "<rect x=\"7\" y=\"6\" width=\"34\" height=\"36\" rx=\"2\" /><circle cx=\"24\" cy=\"20\" r=\"9\" stroke-width=\"1.4\" /><path d=\"M24 13 L29 25 L19 25 Z\" stroke-width=\"1.3\" /><path d=\"M13 36 h5 m4 0 h5 m4 0 h5\" stroke-width=\"1.4\" />",
    bms: "<rect x=\"6\" y=\"9\" width=\"36\" height=\"24\" rx=\"2\" /><path d=\"M11 25 l6 -7 l6 10 l6 -6 l6 3\" stroke-width=\"1.4\" /><path d=\"M18 33 v5 h12 v-5 M14 40 H34\" stroke-width=\"1.4\" />",
    itload: "<rect x=\"7\" y=\"10\" width=\"34\" height=\"22\" rx=\"2\" /><text x=\"24\" y=\"26\" font-family=\"sans-serif\" font-size=\"12\" font-weight=\"700\" text-anchor=\"middle\" fill=\"currentColor\" stroke=\"none\">IT</text><path d=\"M17 38 H31 M24 32 V38\" stroke-width=\"1.5\" />",
    breaker: "<path d=\"M24 4 V15 M24 33 V44\" stroke-width=\"1.8\" /><rect x=\"16\" y=\"15\" width=\"16\" height=\"18\" rx=\"1\" /><path d=\"M18 17 L30 31 M30 17 L18 31\" stroke-width=\"1.6\" />",
    disconnect: "<path d=\"M24 4 V15 M24 33 V44\" stroke-width=\"1.8\" /><circle cx=\"24\" cy=\"16\" r=\"2.4\" fill=\"currentColor\" stroke=\"none\" /><circle cx=\"24\" cy=\"32\" r=\"2.4\" fill=\"currentColor\" stroke=\"none\" /><path d=\"M24 32 L34 16\" stroke-width=\"1.8\" /><path d=\"M15 24 H21\" stroke-width=\"1.2\" stroke-dasharray=\"2 2\" />",
    ats: "<path d=\"M14 4 V12 M34 4 V12\" stroke-width=\"1.6\" /><circle cx=\"14\" cy=\"14\" r=\"2.2\" fill=\"currentColor\" stroke=\"none\" /><circle cx=\"34\" cy=\"14\" r=\"2.2\" fill=\"currentColor\" stroke=\"none\" /><circle cx=\"24\" cy=\"34\" r=\"2.2\" fill=\"currentColor\" stroke=\"none\" /><path d=\"M24 34 L14 14\" stroke-width=\"1.8\" /><path d=\"M24 34 V44\" stroke-width=\"1.6\" /><path d=\"M20 22 a5 5 0 0 0 8 0\" stroke-width=\"1.2\" stroke-dasharray=\"2 2\" />",
    dryCooler: "<rect x=\"5\" y=\"12\" width=\"38\" height=\"24\" rx=\"2\" /><circle cx=\"16\" cy=\"24\" r=\"7\" stroke-width=\"1.4\" /><path d=\"M16 24 L16 17 M16 24 L22 27 M16 24 L10 27\" stroke-width=\"1.2\" /><circle cx=\"32\" cy=\"24\" r=\"7\" stroke-width=\"1.4\" /><path d=\"M32 24 L32 17 M32 24 L38 27 M32 24 L26 27\" stroke-width=\"1.2\" />",
    solarArray: "<path d=\"M10 34 L18 16 H40 L32 34 Z\" /><path d=\"M14.7 28 H36.7 M17.3 22 H39.3 M25 16 L17 34 M32 16 L24 34\" stroke-width=\"1.2\" /><path d=\"M8 10 v4 M14 8 l2 3.5 M4.5 15.5 l3.5 2\" stroke-width=\"1.6\" /><path d=\"M16 34 v6 M34 34 v6\" stroke-width=\"1.6\" />",
    inverter: "<rect x=\"8\" y=\"10\" width=\"32\" height=\"28\" rx=\"2\" /><path d=\"M8 38 L40 10\" stroke-width=\"1.4\" /><path d=\"M13 17 h8 M13 21 h8\" stroke-width=\"1.6\" stroke-dasharray=\"0\" /><path d=\"M13 21 h8\" stroke-width=\"1.6\" stroke-dasharray=\"2 2\" /><path d=\"M26 30 q3 -6 6 0 t6 0\" stroke-width=\"1.6\" />",
    pump: "<circle cx=\"24\" cy=\"26\" r=\"12\" /><path d=\"M24 14 V8 H36\" stroke-width=\"1.6\" /><path d=\"M18 26 h9 M24 20.5 l6 5.5 -6 5.5\" stroke-width=\"1.8\" /><path d=\"M12 40 h24\" stroke-width=\"1.4\" />",
    heatExchanger: "<rect x=\"10\" y=\"10\" width=\"28\" height=\"28\" rx=\"2\" /><path d=\"M10 24 h6 l4 -8 4 16 4 -16 4 16 4 -8 h2\" stroke-width=\"1.6\" /><path d=\"M4 16 h6 M44 32 h-6\" stroke-width=\"1.6\" /><path d=\"M7 13 l3 3 -3 3 M41 29 l-3 3 3 3\" stroke-width=\"1.3\" />",
};
