#!/usr/bin/env python3
"""audit-js-syntax.py — detect JS *parse* errors in inline <script> blocks.

WHY THIS EXISTS
---------------
`audit-script-tags.py` only catches an unescaped ``</script>`` inside a JS
string. It does NOT catch an *unterminated string literal* or raw CSS/HTML
wrongly injected into a JS string — which is exactly the v1.8.0
mobile-responsive patch-tool regression that silently broke ~33 pages
(commit f460741): a single ``SyntaxError: Invalid or unexpected token``
voids the ENTIRE <script> element, so every function (calc engine,
free/pro, login, Export PDF, menus) becomes undefined.

This auditor runs ``node --check`` on every *executable* inline script
block. Non-JS ``<script type=...>`` blocks (JSON-LD, importmap,
speculationrules, templates) are skipped so they are never false positives
— the browser never parses those as JavaScript either.

USAGE
-----
    python3 tools/audit-js-syntax.py            # report, exit 0
    python3 tools/audit-js-syntax.py --strict   # exit 1 if any block fails
    python3 tools/audit-js-syntax.py --list      # one line per broken file

This is a MANDATORY pre-push gate (see CLAUDE.md).
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# <script ...> ... </script>  (non-greedy; first close wins — good enough,
# an actual </script>-in-string is a different auditor's job)
SCRIPT_RE = re.compile(
    r"<script\b([^>]*)>(.*?)</script\s*>", re.IGNORECASE | re.DOTALL
)
TYPE_RE = re.compile(r"""\btype\s*=\s*["']?([^"'\s>]+)""", re.IGNORECASE)
SRC_RE = re.compile(r"""\bsrc\s*=""", re.IGNORECASE)

# Build-GENERATED files that legitimately embed literal <script> tags as
# *documentation text* (inside <code>/<pre>). A line-based regex cannot tell
# quoted-script-docs from a real inline script (that needs DOM nesting), so
# these would false-positive forever and wrongly block the pre-push gate.
# Browser ground-truth (tools/probe-all-pageerrors.mjs) confirms they throw
# zero SyntaxError. changelog.html is regenerated by build-changelog-html.py,
# never hand-edited, and is the only such file on the site.
EXCLUDE_FILES = {"changelog.html"}

# script types the browser does NOT execute as JS -> never flag
NON_JS_TYPES = {
    "application/ld+json",
    "application/json",
    "importmap",
    "speculationrules",
    "text/template",
    "text/x-template",
    "text/html",
    "text/markdown",
}


def iter_html_files() -> list[str]:
    return sorted(
        f for f in os.listdir(ROOT)
        if f.endswith(".html")
        and f not in EXCLUDE_FILES
        and os.path.isfile(os.path.join(ROOT, f))
    )


def check_block(body: str, is_module: bool) -> str | None:
    """Return the first SyntaxError line, or None if the block parses."""
    suffix = ".mjs" if is_module else ".js"
    with tempfile.NamedTemporaryFile(
        "w", suffix=suffix, delete=False, encoding="utf-8"
    ) as fh:
        fh.write(body)
        tmp = fh.name
    try:
        res = subprocess.run(
            ["node", "--check", tmp],
            capture_output=True, text=True, timeout=30,
        )
        if res.returncode == 0:
            return None
        for ln in res.stderr.splitlines():
            if "SyntaxError" in ln:
                return ln.strip()
        return (res.stderr.strip().splitlines() or ["parse failed"])[-1]
    except subprocess.TimeoutExpired:
        return "node --check timed out"
    finally:
        try:
            os.unlink(tmp)
        except OSError:
            pass


def audit() -> list[tuple[str, int, int, str]]:
    """-> list of (file, block_index, approx_start_line, syntax_error)."""
    failures: list[tuple[str, int, int, str]] = []
    for fname in iter_html_files():
        path = os.path.join(ROOT, fname)
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            html = fh.read()
        block_idx = 0
        for m in SCRIPT_RE.finditer(html):
            attrs, body = m.group(1) or "", m.group(2) or ""
            if SRC_RE.search(attrs):
                continue
            tm = TYPE_RE.search(attrs)
            stype = tm.group(1).lower() if tm else ""
            if stype in NON_JS_TYPES:
                continue
            if not body.strip():
                continue
            block_idx += 1
            is_module = stype == "module"
            err = check_block(body, is_module)
            if err:
                start_line = html.count("\n", 0, m.start()) + 1
                failures.append((fname, block_idx, start_line, err))
    return failures


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--strict", action="store_true",
                    help="exit 1 if any inline JS block fails to parse")
    ap.add_argument("--list", action="store_true",
                    help="print only the broken file names")
    args = ap.parse_args()

    failures = audit()
    files = iter_html_files()

    if args.list:
        for f in sorted({x[0] for x in failures}):
            print(f)
    else:
        if failures:
            print(f"JS SYNTAX AUDIT — {len(files)} HTML files\n")
            for fname, idx, line, err in failures:
                print(f"  ✗ {fname}  (inline block #{idx}, ~line {line})")
                print(f"      {err}")
            broken = len({x[0] for x in failures})
            print(f"\nBROKEN: {broken} files, {len(failures)} blocks")
        else:
            print(f"JS SYNTAX AUDIT — {len(files)} HTML files")
            print("CLEAN — every executable inline <script> parses")

    if args.strict and failures:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
