#!/usr/bin/env python3
"""build-explain-db.py — generate js/rz-explain-db.js (window.RZ_EXPLAIN_DB) from:
  1. glossary.html   — the 354-term human-maintained glossary (source of truth)
  2. tools/explain-extra.json — curated super-detail entries (calculator/finance params)
Curated entries WIN on key collision (they're richer). Deterministic output (sorted keys).
Run after editing glossary or explain-extra:  python3 tools/build-explain-db.py
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
GLOSSARY = ROOT / 'glossary.html'
EXTRA = ROOT / 'tools' / 'explain-extra.json'
OUT = ROOT / 'js' / 'rz-explain-db.js'


def strip_tags(html: str) -> str:
    text = re.sub(r'<[^>]+>', ' ', html)
    text = re.sub(r'&amp;', '&', text)
    text = re.sub(r'&lt;', '<', text)
    text = re.sub(r'&gt;', '>', text)
    text = re.sub(r'&nbsp;', ' ', text)
    text = re.sub(r'&#39;|&apos;', "'", text)
    text = re.sub(r'&quot;', '"', text)
    return re.sub(r'\s+', ' ', text).strip()


def parse_glossary() -> dict:
    html = GLOSSARY.read_text(encoding='utf-8')
    entries = {}
    for m in re.finditer(
            r'<div class="term" id="term-([^"]+)">(.*?)(?=<div class="term" id="term-|</section>)',
            html, re.S):
        slug, block = m.group(1), m.group(2)
        name_m = re.search(r'<[^>]*class="term-name"[^>]*>(.*?)</', block, re.S)
        full_m = re.search(r'<[^>]*class="term-full"[^>]*>(.*?)</', block, re.S)
        def_m = re.search(r'<[^>]*class="term-def"[^>]*>(.*?)</(?:p|div)>', block, re.S)
        if not name_m or not def_m:
            continue
        name = strip_tags(name_m.group(1))
        full = strip_tags(full_m.group(1)) if full_m else ''
        entry = {
            't': name + (' (' + full + ')' if full and full.lower() != name.lower() else ''),
            'd': strip_tags(def_m.group(1)),
            'link': 'glossary.html#term-' + slug,
        }
        aliases = [name]
        if full:
            aliases.append(full)
        entry['aliases'] = sorted(set(aliases))
        entries[slug] = entry
    return entries


def main() -> None:
    glossary = parse_glossary()
    extra = {}
    if EXTRA.exists():
        extra = json.loads(EXTRA.read_text(encoding='utf-8')).get('entries', {})
    merged = dict(glossary)
    merged.update(extra)          # curated wins on key collision
    # alias dedupe: if a curated entry claims an alias, strip it from glossary entries
    curated_aliases = set()
    for e in extra.values():
        for a in e.get('aliases', []):
            curated_aliases.add(a.lower())
        curated_aliases.add(e.get('t', '').split(' (')[0].lower())
    for k, e in merged.items():
        if k in extra:
            continue
        kept = [a for a in e.get('aliases', []) if a.lower() not in curated_aliases]
        if kept != e.get('aliases', []):
            e['aliases'] = kept
    # validation
    bad = [k for k, e in merged.items() if not e.get('t') or not e.get('d')]
    if bad:
        print('FAIL: entries missing t/d:', bad[:10])
        sys.exit(1)
    for k, e in merged.items():
        for r in e.get('rel', []):
            if r not in merged:
                print(f'FAIL: {k} rel -> unknown key {r}')
                sys.exit(1)
    body = json.dumps({'version': '1.0.0',
                       'counts': {'glossary': len(glossary), 'curated': len(extra), 'total': len(merged)},
                       'entries': dict(sorted(merged.items()))},
                      ensure_ascii=False, separators=(',', ':'))
    OUT.write_text(
        '/* GENERATED by tools/build-explain-db.py — DO NOT EDIT BY HAND.\n'
        '   Sources: glossary.html (' + str(len(glossary)) + ' terms) + tools/explain-extra.json ('
        + str(len(extra)) + ' curated). See standarization/EXPLAIN_ENGINE_STANDARD.md. */\n'
        'window.RZ_EXPLAIN_DB = ' + body + ';\n',
        encoding='utf-8')
    print(f'WROTE {OUT.name}: glossary {len(glossary)} + curated {len(extra)} = {len(merged)} entries')


if __name__ == '__main__':
    main()
